<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/TitulacionIstpet.Infrastructure/TitulacionIstpet.Infrastructure.csproj" />
    <Content Include="../../../docs/ejemplos/complexivo-diseno-grafico.json" Link="complexivo-diseno-grafico.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
