// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class AcadAsistencias
{
    public int IdAsistencia { get; set; }

    public int IdMatricula { get; set; }

    public int IdSesion { get; set; }

    public string Estado { get; set; }

    public short? MinutosAtraso { get; set; }

    public string Observacion { get; set; }

    public string UsuarioCreacion { get; set; }

    public string UsuarioActualiza { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public virtual Matriculas IdMatriculaNavigation { get; set; }

    public virtual AcadSesiones IdSesionNavigation { get; set; }
}
