// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class AcadAsistenciasHistorial
{
    public ulong IdHistorial { get; set; }

    public int IdAsistencia { get; set; }

    public int IdSesion { get; set; }

    public int IdMatricula { get; set; }

    public string EstadoAnterior { get; set; }

    public string EstadoNuevo { get; set; }

    public string Usuario { get; set; }

    public string Rol { get; set; }

    public string Motivo { get; set; }

    public string IpAddress { get; set; }

    public DateTime? Fecha { get; set; }
}
