// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class AcadSesiones
{
    public int IdSesion { get; set; }

    public int IdAsignacion { get; set; }

    public int IdFecha { get; set; }

    public bool NumeroBloque { get; set; }

    public string Tema { get; set; }

    public string Estado { get; set; }

    public string Observacion { get; set; }

    public bool? Activo { get; set; }

    public string UsuarioCreacion { get; set; }

    public string UsuarioActualiza { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public DateTime? FechaCierre { get; set; }

    public virtual AsignacionesProfesores IdAsignacionNavigation { get; set; }

    public virtual FechasHorarios IdFechaNavigation { get; set; }

    public virtual ICollection<AcadAsistencias> AcadAsistencias { get; set; } = new List<AcadAsistencias>();
}
