// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class AceptacionesUsuarios
{
    public int IdAceptacionUsuario { get; set; }

    public string IdUsuario { get; set; }

    public int? IdTermino { get; set; }

    public string Sistema { get; set; }

    public DateTime? FechaRegistro { get; set; }

    public string IpOrigen { get; set; }

    public string Dispositivo { get; set; }
}