// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class AdjuntosImagenes
{
    public int IdAdjuntosImagenes { get; set; }

    public string NombreArchivos { get; set; }

    public string Extension { get; set; }

    public string MimeTypes { get; set; }

    public int? TamanioBytes { get; set; }

    public string Ruta { get; set; }

    public virtual ICollection<BienCasoDesarrolloDoc> BienCasoDesarrolloDoc { get; set; } = new List<BienCasoDesarrolloDoc>();

    public virtual ICollection<BienCasoRequerimiento> BienCasoRequerimiento { get; set; } = new List<BienCasoRequerimiento>();

    public virtual ICollection<BienMotivoApertura> BienMotivoApertura { get; set; } = new List<BienMotivoApertura>();

    public virtual ICollection<BienPostulacionRequisitosBecas> BienPostulacionRequisitosBecas { get; set; } = new List<BienPostulacionRequisitosBecas>();

    public virtual ICollection<CarrerasAdjuntos> CarrerasAdjuntos { get; set; } = new List<CarrerasAdjuntos>();

    public virtual ICollection<PlantillaContrato> PlantillaContratoIdFondoNavigation { get; set; } = new List<PlantillaContrato>();

    public virtual ICollection<PlantillaContrato> PlantillaContratoIdSelloNavigation { get; set; } = new List<PlantillaContrato>();

    public virtual ICollection<TitulPostulacionAlumnosRequisitosModalidad> TitulPostulacionAlumnosRequisitosModalidad { get; set; } = new List<TitulPostulacionAlumnosRequisitosModalidad>();
}