// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class AlumnosHabilidades
{
    public int IdalumnosHabilidades { get; set; }

    public string IdAlumno { get; set; }

    public int Idhabilidades { get; set; }

    public string Nivel { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public virtual Habilidades IdhabilidadesNavigation { get; set; }
}