// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class AlumnosSucesos
{
    public int IdSuceso { get; set; }

    public string IdAlumno { get; set; }

    public int? IdMatricula { get; set; }

    public DateTime FechaRegistro { get; set; }

    public string Observacion { get; set; }

    public string Usuario { get; set; }
}