// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Alumnos
{
    public string IdAlumno { get; set; }

    public string TipoDocumento { get; set; }

    public string ApellidoPaterno { get; set; }

    public string ApellidoMaterno { get; set; }

    public string PrimerNombre { get; set; }

    public string SegundoNombre { get; set; }

    public DateOnly? FechaNacimiento { get; set; }

    public string Direccion { get; set; }

    public string Telefono { get; set; }

    public string Celular { get; set; }

    public string Email { get; set; }

    public string CiudadNacimiento { get; set; }

    public string ProvinciaNacimiento { get; set; }

    public byte[] Foto { get; set; }

    public string Sexo { get; set; }

    public string Nacionalidad { get; set; }

    public int? IdNivel { get; set; }

    public string IdPeriodo { get; set; }

    public int? IdSeccion { get; set; }

    public int? IdModalidad { get; set; }

    public int? IdInstitucion { get; set; }

    public string TituloColegio { get; set; }

    public DateTime? FechaInscripcion { get; set; }

    public string ParroquiaNacimiento { get; set; }

    public string NombrePadre { get; set; }

    public string OcupacionPadre { get; set; }

    public string NacionalidadPadre { get; set; }

    public string NombreMadre { get; set; }

    public string OcupacionMadre { get; set; }

    public string NacionalidadMadre { get; set; }

    public string BarrioResidencia { get; set; }

    public string ParroquiaResidencia { get; set; }

    public string CiudadResidencia { get; set; }

    public string TipoSangre { get; set; }

    public string UserAlumno { get; set; }

    public string Password { get; set; }

    public int? IdDiscapacidad { get; set; }

    public int? IdEtnia { get; set; }

    public int? IdNacionalidad { get; set; }

    public int? PorcentajeDiscapacidad { get; set; }

    public string CarnetConadis { get; set; }

    public string EmailInstitucional { get; set; }

    public bool? PrimerIngreso { get; set; }

    public string Archivofoto { get; set; }

    public bool? FotoAprobada { get; set; }

    public int? IdEstadoCivil { get; set; }

    public int? IdGeneroAlumno { get; set; }

    public int? IdNacionalidadEtnica { get; set; }

    public int? IdParroquiaResidencia { get; set; }

    public string TipoInstitucion { get; set; }

    public virtual ICollection<BienDatosEducacion> BienDatosEducacion { get; set; } = new List<BienDatosEducacion>();

    public virtual ICollection<BienFichaSocioeconomica> BienFichaSocioeconomica { get; set; } = new List<BienFichaSocioeconomica>();

    public virtual ICollection<BienParentezcosAlumno> BienParentezcosAlumno { get; set; } = new List<BienParentezcosAlumno>();

    public virtual ICollection<ExperienciasLaborales> ExperienciasLaborales { get; set; } = new List<ExperienciasLaborales>();

    public virtual Estadocivil IdEstadoCivilNavigation { get; set; }

    public virtual BienGeneroAlumno IdGeneroAlumnoNavigation { get; set; }

    public virtual Etnias IdNacionalidadEtnicaNavigation { get; set; }

    public virtual Parroquias IdParroquiaResidenciaNavigation { get; set; }

    public virtual ICollection<Matriculas> Matriculas { get; set; } = new List<Matriculas>();
}