// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class AlumnosActaConduccion
{
    public string Idalumno { get; set; }

    public int? NumeroActa { get; set; }

    public DateOnly? FechaGrado { get; set; }

    public string Idperiodo { get; set; }
}