// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class AlumnosInscripcionesIngles
{
    public string IdAlumno { get; set; }

    public string IdPeriodo { get; set; }

    public DateTime FechaRegistro { get; set; }

    public string UserInscripcion { get; set; }

    public decimal? Puntaje { get; set; }

    public int? IdAsignatura { get; set; }

    public int? IdMalla { get; set; }

    public string Observacion { get; set; }
}