// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class AsignacionesPropedeutico
{
    public int IdCarrera { get; set; }

    public int IdAsignatura { get; set; }

    public bool? Activa { get; set; }
}