// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class AsignacionesProfesoresGrado
{
    public string IdProfesor { get; set; }

    public int IdAsignatura { get; set; }

    public string IdPeriodo { get; set; }

    public int IdModalidad { get; set; }

    public int IdSeccion { get; set; }

    public int IdNivel { get; set; }

    public string Paralelo { get; set; }

    public bool? Activo { get; set; }
}