// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Asignaturas
{
    public int IdAsignatura { get; set; }

    public string Asignatura { get; set; }

    public bool? Anulada { get; set; }

    public string Codigo { get; set; }

    public bool? ExtraCurricular { get; set; }

    public virtual ICollection<Calificaciones> Calificaciones { get; set; } = new List<Calificaciones>();

    public virtual ICollection<ContratosAsignaturas> ContratosAsignaturas { get; set; } = new List<ContratosAsignaturas>();

    public virtual ICollection<Detallemallas> Detallemallas { get; set; } = new List<Detallemallas>();

    public virtual ICollection<Prerequisitos> Prerequisitos { get; set; } = new List<Prerequisitos>();

    public virtual ICollection<Solicitudescalificaciones> Solicitudescalificaciones { get; set; } = new List<Solicitudescalificaciones>();
}