// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class AsignaturasComplementosFormacion
{
    public int IdAsignatura { get; set; }

    public int? IdCarrera { get; set; }

    public string Asignatura { get; set; }

    public bool? Activo { get; set; }
}