// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class AsignacionInstructoresVehiculos
{
    public int IdAsignacion { get; set; }

    public int IdVehiculo { get; set; }

    public string IdProfesor { get; set; }

    public DateOnly? FechaAsignacion { get; set; }

    public DateOnly? FechaSalidad { get; set; }

    public bool? Activo { get; set; }

    public string UsuarioAsigna { get; set; }

    public string UsuarioDesactiva { get; set; }

    public string Observacion { get; set; }
}