// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class AuditLogs
{
    public int Id { get; set; }

    public string Usuario { get; set; }

    public string Accion { get; set; }

    public string EntidadId { get; set; }

    public string Detalles { get; set; }

    public string IpOrigen { get; set; }

    public DateTime FechaHora { get; set; }
}