// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class AuditoriaPagos
{
    public int? Idpago { get; set; }

    public int? Idmatricula { get; set; }

    public DateTime Fecha { get; set; }

    public string NumeroDeposito { get; set; }

    public string Cuenta { get; set; }

    public float? Valor { get; set; }

    public int? NumRegistro { get; set; }

    public string Usuario { get; set; }
}