// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class BienTipoDesarrollo
{
    public int IdTipoDesarrollo { get; set; }

    public string Detalle { get; set; }

    public bool EsCierre { get; set; }

    public bool EsActivo { get; set; }

    public virtual ICollection<BienCasoDesarrollo> BienCasoDesarrollo { get; set; } = new List<BienCasoDesarrollo>();
}