// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class BienDatosEducacion
{
    public int IdDatosEducacion { get; set; }

    public string NombreCurso { get; set; }

    public string NombreInstitucion { get; set; }

    public bool EsIstpet { get; set; }

    public string NivelEducacion { get; set; }

    public bool EstaCursando { get; set; }

    public bool EsPresencial { get; set; }

    public bool EsBecado { get; set; }

    public string TipoEducacion { get; set; }

    public string IdAlumno { get; set; }

    public virtual Alumnos IdAlumnoNavigation { get; set; }
}