// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class BienRequerimientosMotivoApertura
{
    public int IdRequerimientoMotivoApertura { get; set; }

    public string Detalle { get; set; }

    public int IdMotivoApertura { get; set; }

    public bool EsObligatorio { get; set; }

    public bool EsActivo { get; set; }

    public virtual ICollection<BienCasoRequerimiento> BienCasoRequerimiento { get; set; } = new List<BienCasoRequerimiento>();

    public virtual BienMotivoApertura IdMotivoAperturaNavigation { get; set; }
}