// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class BienResolucionesTribunales
{
    public int IdResolucionesTribunales { get; set; }

    public int IdPostulacionesBecas { get; set; }

    public int IdUsuarioRegistra { get; set; }

    public string IdPeriodo { get; set; }

    public string Resolucion { get; set; }

    public decimal PorcentajeFinal { get; set; }

    public string Observacion { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public DateTime FechaRegistro { get; set; }

    public virtual ICollection<BienApoyoFinanciero> BienApoyoFinanciero { get; set; } = new List<BienApoyoFinanciero>();

    public virtual BienVotosTribunales BienVotosTribunales { get; set; }

    public virtual Periodos IdPeriodoNavigation { get; set; }

    public virtual BienPostulacionesBecas IdPostulacionesBecasNavigation { get; set; }

    public virtual Usuarios IdUsuarioRegistraNavigation { get; set; }
}