// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class BienCaso
{
    public int IdCaso { get; set; }

    public string CodigoCaso { get; set; }

    public int IdMotivoApertura { get; set; }

    public string IdPeriodo { get; set; }

    public int IdUsuarioResponsableCaso { get; set; }

    public string AccionesRealizadas { get; set; }

    public string ConclusionesCierre { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public string Estado { get; set; }

    public virtual ICollection<BienCasoDesarrollo> BienCasoDesarrollo { get; set; } = new List<BienCasoDesarrollo>();

    public virtual ICollection<BienCasoRequerimiento> BienCasoRequerimiento { get; set; } = new List<BienCasoRequerimiento>();

    public virtual ICollection<BienUsuarioCaso> BienUsuarioCaso { get; set; } = new List<BienUsuarioCaso>();

    public virtual BienMotivoApertura IdMotivoAperturaNavigation { get; set; }

    public virtual Periodos IdPeriodoNavigation { get; set; }

    public virtual Usuarios IdUsuarioResponsableCasoNavigation { get; set; }
}