// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class BienServiciosFichas
{
    public int IdServicioFicha { get; set; }

    public bool TieneServicio { get; set; }

    public int IdTipoServicio { get; set; }

    public int IdFichaSocioEconomica { get; set; }

    public virtual BienFichaSocioeconomica IdFichaSocioEconomicaNavigation { get; set; }

    public virtual BienTipoServicios IdTipoServicioNavigation { get; set; }
}