// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class BienParametroRequisitoBeca
{
    public int IdParametroRequisitoBeca { get; set; }

    public int IdRequistosBeca { get; set; }

    public bool EsObligatorio { get; set; }

    public bool EsActivo { get; set; }

    public int IdTipoApoyoFinanciero { get; set; }

    public virtual ICollection<BienPostulacionRequisitosBecas> BienPostulacionRequisitosBecas { get; set; } = new List<BienPostulacionRequisitosBecas>();

    public virtual BienRequisitosBeca IdRequistosBecaNavigation { get; set; }

    public virtual BienTipoApoyoFinanciero IdTipoApoyoFinancieroNavigation { get; set; }
}