// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class BienNivelInstruccion
{
    public int IdNivelInstruccion { get; set; }

    public string Detalle { get; set; }

    public virtual ICollection<BienParentezcosAlumno> BienParentezcosAlumno { get; set; } = new List<BienParentezcosAlumno>();
}