// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class BienCasoRequerimiento
{
    public int IdCasoRequerimiento { get; set; }

    public int IdCaso { get; set; }

    public int IdRequerimientoMotivoApertura { get; set; }

    /// <summary>
    /// snapshot del catalogo al abrir
    /// </summary>
    public string Detalle { get; set; }

    /// <summary>
    /// snapshot del catalogo al abrir
    /// </summary>
    public bool EsObligatorio { get; set; }

    public bool Cumplido { get; set; }

    public int? IdAdjuntosImagenes { get; set; }

    public int? IdUsuarioCumplio { get; set; }

    public DateTime? FechaCumplimiento { get; set; }

    public string Observacion { get; set; }

    public virtual AdjuntosImagenes IdAdjuntosImagenesNavigation { get; set; }

    public virtual BienCaso IdCasoNavigation { get; set; }

    public virtual BienRequerimientosMotivoApertura IdRequerimientoMotivoAperturaNavigation { get; set; }

    public virtual Usuarios IdUsuarioCumplioNavigation { get; set; }
}