// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class BienTipoCargoTribunal
{
    public int IdTipoCargoTribunal { get; set; }

    public string Detalle { get; set; }

    public bool? EsRector { get; set; }

    public virtual ICollection<BienTribunal> BienTribunal { get; set; } = new List<BienTribunal>();

    public virtual ICollection<BienVotosTribunales> BienVotosTribunales { get; set; } = new List<BienVotosTribunales>();
}