// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class BienTipoSujeto
{
    public int IdTipoSujeto { get; set; }

    public string Detalle { get; set; }

    public bool EsActivo { get; set; }

    public virtual ICollection<BienUsuarioCaso> BienUsuarioCaso { get; set; } = new List<BienUsuarioCaso>();
}