// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class BienDetalleVivienda
{
    public string IdAlumno { get; set; }

    public string TipoDeVivienda { get; set; }

    public int EspaciosFisicos { get; set; }

    public int Dormitorios { get; set; }

    public string Referencia { get; set; }

    public int? MiembrosHogar { get; set; }

    public int? AdultosVivienda { get; set; }

    public int? NiñosVivienda { get; set; }

    public bool? BonoDesarrolloHumano { get; set; }

    public decimal? IngresoPromedioHogar { get; set; }

    public int IdFichaSocioEconomica { get; set; }

    public virtual BienFichaSocioeconomica IdFichaSocioEconomicaNavigation { get; set; }
}