// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class BienCasoDesarrollo
{
    public int IdCasoDesarrollo { get; set; }

    public int IdCaso { get; set; }

    public int? IdCasoDesarrolloPadre { get; set; }

    public int IdTipoDesarrollo { get; set; }

    public string Titulo { get; set; }

    public string Descripcion { get; set; }

    public string Observaciones { get; set; }

    public int Orden { get; set; }

    public string Estado { get; set; }

    public DateTime FechaPlanificada { get; set; }

    public DateTime? FechaReal { get; set; }

    public int? IdUsuarioResponsable { get; set; }

    public int? CasoAbierto { get; set; }

    public virtual ICollection<BienAsistentesDesarrollo> BienAsistentesDesarrollo { get; set; } = new List<BienAsistentesDesarrollo>();

    public virtual ICollection<BienCasoDesarrolloDoc> BienCasoDesarrolloDoc { get; set; } = new List<BienCasoDesarrolloDoc>();

    public virtual BienCasoDesarrollo IdCasoDesarrolloPadreNavigation { get; set; }

    public virtual BienCaso IdCasoNavigation { get; set; }

    public virtual BienTipoDesarrollo IdTipoDesarrolloNavigation { get; set; }

    public virtual Usuarios IdUsuarioResponsableNavigation { get; set; }

    public virtual ICollection<BienCasoDesarrollo> InverseIdCasoDesarrolloPadreNavigation { get; set; } = new List<BienCasoDesarrollo>();
}