// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class BienPostulacionRequisitosBecas
{
    public int IdPostulacionBecaDocumentos { get; set; }

    public int IdParametroRequisitoBeca { get; set; }

    public string EstadoDocumento { get; set; }

    public string ObservacionBienestar { get; set; }

    public DateTime? FechaValidacionBienestar { get; set; }

    public DateTime FechaRegistro { get; set; }

    public bool EsActivo { get; set; }

    public int IdPostulacionesBecas { get; set; }

    public int? IdUsuarioBienestar { get; set; }

    public bool? RequisitoBool { get; set; }

    public int? RequisitoAdjunto { get; set; }

    public virtual BienParametroRequisitoBeca IdParametroRequisitoBecaNavigation { get; set; }

    public virtual BienPostulacionesBecas IdPostulacionesBecasNavigation { get; set; }

    public virtual Usuarios IdUsuarioBienestarNavigation { get; set; }

    public virtual AdjuntosImagenes RequisitoAdjuntoNavigation { get; set; }
}