// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class BienTipoServicios
{
    public int IdTipoServicio { get; set; }

    public string Nombre { get; set; }

    public bool EsActivo { get; set; }

    public virtual ICollection<BienServiciosFichas> BienServiciosFichas { get; set; } = new List<BienServiciosFichas>();
}