// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class BienMotivosBeca
{
    public int IdMotivosBeca { get; set; }

    public bool EsActivo { get; set; }

    public bool? EsDefault { get; set; }

    public int IdTipoApoyoFinanciero { get; set; }

    public int IdPorcentajeBecaMinimo { get; set; }

    public int? IdPorcentajeBecaMaximo { get; set; }

    public virtual ICollection<BienPostulacionesBecas> BienPostulacionesBecas { get; set; } = new List<BienPostulacionesBecas>();

    public virtual BienPorcentajeBeca IdPorcentajeBecaMinimoNavigation { get; set; }

    public virtual BienTipoApoyoFinanciero IdTipoApoyoFinancieroNavigation { get; set; }
}