// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class BienTipoVivienda
{
    public int IdTipoVivienda { get; set; }

    public string Detalle { get; set; }

    public virtual ICollection<BienFichaSocioeconomica> BienFichaSocioeconomica { get; set; } = new List<BienFichaSocioeconomica>();
}