// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class BienTribunal
{
    public int IdUsuario { get; set; }

    public bool EsActivo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public int? IdTipoCargoTribunal { get; set; }

    public virtual ICollection<BienVotosTribunales> BienVotosTribunales { get; set; } = new List<BienVotosTribunales>();

    public virtual BienTipoCargoTribunal IdTipoCargoTribunalNavigation { get; set; }

    public virtual Usuarios IdUsuarioNavigation { get; set; }
}