// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class BienRequisitosBeca
{
    public int IdRequistosBeca { get; set; }

    public string Requisito { get; set; }

    public string TipoRequisito { get; set; }

    public bool EsActivo { get; set; }

    public virtual ICollection<BienParametroRequisitoBeca> BienParametroRequisitoBeca { get; set; } = new List<BienParametroRequisitoBeca>();
}