// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class BienParentescos
{
    public int IdParentezco { get; set; }

    public string Nombre { get; set; }

    public bool EsPadre { get; set; }

    public bool EsMadre { get; set; }

    public virtual ICollection<BienParentezcosAlumno> BienParentezcosAlumno { get; set; } = new List<BienParentezcosAlumno>();
}