// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class BienTipoConvocatoria
{
    public int IdTipoConvocatoria { get; set; }

    public string Detalle { get; set; }

    public bool EsActivo { get; set; }

    public bool EsInformativo { get; set; }

    public bool Bloquea { get; set; }

    public virtual ICollection<BienConvocatoriasBecas> BienConvocatoriasBecas { get; set; } = new List<BienConvocatoriasBecas>();
}