// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class BienDatosEconomicos
{
    public int IdFichaSocioEconomica { get; set; }

    public bool FamiliaRecibeBono { get; set; }

    public string TipoActividadEconomica { get; set; }

    public decimal IngresosPropios { get; set; }

    public string EmpleaIngresos { get; set; }

    public string NombreBono { get; set; }

    public virtual BienFichaSocioeconomica IdFichaSocioEconomicaNavigation { get; set; }
}