// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class BienTipoApoyoFinanciero
{
    public int IdTipoApoyoFinanciero { get; set; }

    public int? IdBienApoyo { get; set; }

    public string NombreApoyo { get; set; }

    public bool EsActivo { get; set; }

    public virtual ICollection<BienMotivosBeca> BienMotivosBeca { get; set; } = new List<BienMotivosBeca>();

    public virtual ICollection<BienParametroRequisitoBeca> BienParametroRequisitoBeca { get; set; } = new List<BienParametroRequisitoBeca>();
}