// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class BienCasoDesarrolloDoc
{
    public int IdCasoDesarrolloDoc { get; set; }

    public int IdCasoDesarrollo { get; set; }

    public int IdAdjuntosImagenes { get; set; }

    public virtual AdjuntosImagenes IdAdjuntosImagenesNavigation { get; set; }

    public virtual BienCasoDesarrollo IdCasoDesarrolloNavigation { get; set; }
}