// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class BienFichaSocioeconomica
{
    public int IdFichaSocioEconomica { get; set; }

    public int IdTipoVivienda { get; set; }

    public int MiembrosHogar { get; set; }

    public int MiembrosAdulto { get; set; }

    public int MiembrosNinos { get; set; }

    public DateTime FechaRegistro { get; set; }

    public bool EstudiaOtroSitio { get; set; }

    public int EspaciosFisicosVivienda { get; set; }

    public int NumeroDormitorioriosVivienda { get; set; }

    public string IdAlumno { get; set; }

    public bool? RequiereActualizacion { get; set; }

    public string RazonActualizacion { get; set; }

    public string UltimaFechaActualizacion { get; set; }

    public string IdPeriodo { get; set; }

    public virtual BienDatosEconomicos BienDatosEconomicos { get; set; }

    public virtual ICollection<BienDetalleVivienda> BienDetalleVivienda { get; set; } = new List<BienDetalleVivienda>();

    public virtual ICollection<BienServiciosFichas> BienServiciosFichas { get; set; } = new List<BienServiciosFichas>();

    public virtual Alumnos IdAlumnoNavigation { get; set; }

    public virtual Periodos IdPeriodoNavigation { get; set; }

    public virtual BienTipoVivienda IdTipoViviendaNavigation { get; set; }
}