// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class BienPermisosSalidasAlumnos
{
    public int IdPermisosSalidasAlumnos { get; set; }

    public int IdMatricula { get; set; }

    public string Razon { get; set; }

    public DateTime? Fecha { get; set; }

    public string Estado { get; set; }

    public int IdUsuario { get; set; }

    public DateTime? FechaRetorno { get; set; }

    public virtual Matriculas IdMatriculaNavigation { get; set; }

    public virtual Usuarios IdUsuarioNavigation { get; set; }
}