// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class BienPostulacionesBecas
{
    public int IdPostulacionesBecas { get; set; }

    public int? IdConvocatoriasBecas { get; set; }

    public int? IdMotivosBeca { get; set; }

    public int? IdUsuarioBienestar { get; set; }

    public int IdMatricula { get; set; }

    public DateOnly FechaRegistro { get; set; }

    public string EstadoBienestar { get; set; }

    public string ObservacionBienestar { get; set; }

    public bool EsActivo { get; set; }

    public DateTime? FechaValidacionBienestar { get; set; }

    public DateTime? FechaActualizado { get; set; }

    public virtual ICollection<BienPostulacionRequisitosBecas> BienPostulacionRequisitosBecas { get; set; } = new List<BienPostulacionRequisitosBecas>();

    public virtual ICollection<BienResolucionesTribunales> BienResolucionesTribunales { get; set; } = new List<BienResolucionesTribunales>();

    public virtual BienConvocatoriasBecas IdConvocatoriasBecasNavigation { get; set; }

    public virtual Matriculas IdMatriculaNavigation { get; set; }

    public virtual BienMotivosBeca IdMotivosBecaNavigation { get; set; }

    public virtual Usuarios IdUsuarioBienestarNavigation { get; set; }
}