// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class BienVotosTribunales
{
    public int IdVotosTribunales { get; set; }

    public string Estado { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int IdResolucionesTribunales { get; set; }

    public int IdUsuarioTribunal { get; set; }

    public string Observaciones { get; set; }

    public int? IdCargoOcupado { get; set; }

    public virtual BienTipoCargoTribunal IdCargoOcupadoNavigation { get; set; }

    public virtual BienResolucionesTribunales IdResolucionesTribunalesNavigation { get; set; }

    public virtual BienTribunal IdUsuarioTribunalNavigation { get; set; }
}