// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class BienUsuarioCaso
{
    public int IdUsuarioCaso { get; set; }

    public int IdTipoSujeto { get; set; }

    public int IdUsuario { get; set; }

    public int IdCaso { get; set; }

    public string Rol { get; set; }

    public string Detalle { get; set; }

    public virtual ICollection<BienAsistentesDesarrollo> BienAsistentesDesarrollo { get; set; } = new List<BienAsistentesDesarrollo>();

    public virtual BienCaso IdCasoNavigation { get; set; }

    public virtual BienTipoSujeto IdTipoSujetoNavigation { get; set; }

    public virtual Usuarios IdUsuarioNavigation { get; set; }
}