// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class BienConvocatoriasBecas
{
    public int IdConvocatoriasBecas { get; set; }

    public DateOnly FechaInicio { get; set; }

    public DateOnly? FechaFin { get; set; }

    public int? IdDetalleCronograma { get; set; }

    public int IdTipoConvocatoria { get; set; }

    public virtual ICollection<BienPostulacionesBecas> BienPostulacionesBecas { get; set; } = new List<BienPostulacionesBecas>();

    public virtual CronDetalleCronograma IdDetalleCronogramaNavigation { get; set; }

    public virtual BienTipoConvocatoria IdTipoConvocatoriaNavigation { get; set; }
}