// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class CalificacionesPropedeutico
{
    public string IdAlumno { get; set; }

    public int IdAsignatura { get; set; }

    public string IdPeriodo { get; set; }

    public decimal? Nota1 { get; set; }

    public bool? Aprobado { get; set; }

    public string Observacion { get; set; }
}