// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class CampoEspecificoUnesco
{
    public int IdCampospecificoUnesco { get; set; }

    public int? IdCampoAmplioUnesco { get; set; }

    public string NombreEspecifico { get; set; }

    public string CodigoEspecifico { get; set; }

    public bool? Activo { get; set; }

    public virtual ICollection<CampoDetalladoUnesco> CampoDetalladoUnesco { get; set; } = new List<CampoDetalladoUnesco>();

    public virtual CampoAmplioUnesco IdCampoAmplioUnescoNavigation { get; set; }
}