// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class CampoDetalladoUnesco
{
    public int IdCampoDetalladoUnesco { get; set; }

    public int? IdCampospecificoUnesco { get; set; }

    public string NombreDetallado { get; set; }

    public string CodigoDetallado { get; set; }

    public bool? Activo { get; set; }

    public virtual CampoEspecificoUnesco IdCampospecificoUnescoNavigation { get; set; }

    public virtual ICollection<TitulosEnCurso> TitulosEnCurso { get; set; } = new List<TitulosEnCurso>();

    public virtual ICollection<TitulosProfesores> TitulosProfesores { get; set; } = new List<TitulosProfesores>();

    public virtual ICollection<Vinculacionproyectos> Vinculacionproyectos { get; set; } = new List<Vinculacionproyectos>();
}