// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class CargosOfertas
{
    public int IdcargosOfertas { get; set; }

    public string NombreCargo { get; set; }

    public virtual ICollection<OfertasLaborales> OfertasLaborales { get; set; } = new List<OfertasLaborales>();
}