// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class CarrerasAdjuntos
{
    public int IdCarrerasAdjuntos { get; set; }

    public int IdCarrera { get; set; }

    public int IdAdjuntosImagenes { get; set; }

    public virtual AdjuntosImagenes IdAdjuntosImagenesNavigation { get; set; }

    public virtual Carreras IdCarreraNavigation { get; set; }
}