// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Carreras
{
    public int IdCarrera { get; set; }

    public string Carrera { get; set; }

    public DateOnly? FechaCreacion { get; set; }

    public bool? Activa { get; set; }

    public string DirectorCarrera { get; set; }

    public int? NumeroCreditos { get; set; }

    public int? OrdenCarrera { get; set; }

    public int? NumeroAlumnos { get; set; }

    public bool? RevisaArrastres { get; set; }

    public string CodigoCases { get; set; }

    public string AliasCarrera { get; set; }

    public bool? BolsaEmpleo { get; set; }

    public bool? EsInstituto { get; set; }

    public virtual ICollection<CarrerasAdjuntos> CarrerasAdjuntos { get; set; } = new List<CarrerasAdjuntos>();

    public virtual ICollection<Cursos> Cursos { get; set; } = new List<Cursos>();

    public virtual ICollection<Espacios> Espacios { get; set; } = new List<Espacios>();

    public virtual ICollection<FechasPagosCuotas> FechasPagosCuotas { get; set; } = new List<FechasPagosCuotas>();

    public virtual ICollection<Mallas> Mallas { get; set; } = new List<Mallas>();

    public virtual ICollection<ModalidadesCarreras> ModalidadesCarreras { get; set; } = new List<ModalidadesCarreras>();

    public virtual ICollection<OfertasCarreras> OfertasCarreras { get; set; } = new List<OfertasCarreras>();

    public virtual ICollection<ProfesoresCarrerasPeriodos> ProfesoresCarrerasPeriodos { get; set; } = new List<ProfesoresCarrerasPeriodos>();

    public virtual ICollection<Vinculacionproyectoscarreras> Vinculacionproyectoscarreras { get; set; } = new List<Vinculacionproyectoscarreras>();
}