// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class CategoriasActividades
{
    public int IdCategoria { get; set; }

    public string Categoria { get; set; }

    public bool? EsDocencia { get; set; }

    public bool? Activo { get; set; }

    public bool? Porcentaje { get; set; }

    public virtual ICollection<Seddinstrumentos> Seddinstrumentos { get; set; } = new List<Seddinstrumentos>();

    public virtual ICollection<SubcategoriasActividades> SubcategoriasActividades { get; set; } = new List<SubcategoriasActividades>();
}