// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Clausulas
{
    public int IdClausulas { get; set; }

    public string NombreClausula { get; set; }

    public int? Orden { get; set; }

    public bool? EsActivo { get; set; }

    public virtual ICollection<PlantillaClausulas> PlantillaClausulas { get; set; } = new List<PlantillaClausulas>();
}