// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class CondAlumnosVehiculos
{
    public int IdAsignacion { get; set; }

    public string IdAlumno { get; set; }

    public int IdVehiculo { get; set; }

    public string IdPeriodo { get; set; }

    public string IdProfesor { get; set; }

    public DateTime FechaAsignacion { get; set; }

    public DateOnly? FechaInicio { get; set; }

    public DateOnly? FechaFin { get; set; }

    public bool? Activa { get; set; }

    public string Observacion { get; set; }
}