// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Configsharepoint
{
    public int IdSharePoint { get; set; }

    public string ClientId { get; set; }

    public string TenanId { get; set; }

    public string ClientSecret { get; set; }

    public string AppId { get; set; }

    public string RedirectUrl { get; set; }

    public string TenantName { get; set; }

    public string SiteName { get; set; }

    public string SiteId { get; set; }

    public string ListId { get; set; }

    public string DriveId { get; set; }

    public bool? EsActivo { get; set; }

    public DateOnly? FechaCreado { get; set; }

    public DateOnly? FechaActualizado { get; set; }

    public string Correo { get; set; }

    public string Password { get; set; }
}