// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class ContratosAsignaturas
{
    public int IdContratosAsignaturas { get; set; }

    public int IdContratos { get; set; }

    public int IdAsignatura { get; set; }

    public string IdPeriodo { get; set; }

    public int? Horas { get; set; }

    public bool? EsActivo { get; set; }

    public int? IdAsignacion { get; set; }

    public string Paralelo { get; set; }

    public int? IdModalidad { get; set; }

    public int? IdSeccion { get; set; }

    public int? IdNivel { get; set; }

    public bool? Pagada { get; set; }

    public decimal? ValorHora { get; set; }

    public virtual Asignaturas IdAsignaturaNavigation { get; set; }

    public virtual Contratos IdContratosNavigation { get; set; }

    public virtual Periodos IdPeriodoNavigation { get; set; }
}