// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Contratos
{
    public int IdContratos { get; set; }

    public int IdInstitucionesInstituto { get; set; }

    public string IdProfesor { get; set; }

    public int IdDedicacionCategorias { get; set; }

    public int? IdTiposContratos { get; set; }

    public int? IdRelacionIes { get; set; }

    public int? Iddepartamentos { get; set; }

    public int? IdCargoInstituto { get; set; }

    public string NumeroContrato { get; set; }

    public bool? EsAdendum { get; set; }

    public string ContratoVinculado { get; set; }

    public DateOnly? FechaRegistro { get; set; }

    public DateOnly? FechaInicio { get; set; }

    public DateOnly? FechaFinal { get; set; }

    public bool? EsActivo { get; set; }

    public string ArchivoContrato { get; set; }

    public string ArchivoLegalizado { get; set; }

    public string ArchivoFiniquito { get; set; }

    public string ArchivoLegalizadoSalida { get; set; }

    public bool? IngresoConcurso { get; set; }

    public string UsuarioCreo { get; set; }

    public string UsuariosModifico { get; set; }

    public DateOnly? FechaModifico { get; set; }

    public DateOnly? Reingreso { get; set; }

    public virtual ICollection<ContratosAsignaturas> ContratosAsignaturas { get; set; } = new List<ContratosAsignaturas>();

    public virtual ICollection<ContratosFacturas> ContratosFacturas { get; set; } = new List<ContratosFacturas>();

    public virtual ICollection<ExtrasContratos> ExtrasContratos { get; set; } = new List<ExtrasContratos>();

    public virtual DedicacionCategorias IdDedicacionCategoriasNavigation { get; set; }

    public virtual InstitucionesInstituto IdInstitucionesInstitutoNavigation { get; set; }

    public virtual Profesores IdProfesorNavigation { get; set; }

    public virtual ICollection<ProfesoresMotivoSalida> ProfesoresMotivoSalida { get; set; } = new List<ProfesoresMotivoSalida>();

    public virtual ICollection<SueldosContratos> SueldosContratos { get; set; } = new List<SueldosContratos>();
}