// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class ContratosFacturas
{
    public int IdFacturasContratos { get; set; }

    public int IdContratos { get; set; }

    public DateOnly? PeriodoFactura { get; set; }

    public string NumeroFactura { get; set; }

    public decimal? ValorFacturado { get; set; }

    public virtual Contratos IdContratosNavigation { get; set; }
}