// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class CronTipoProceso
{
    public int IdTipoProceso { get; set; }

    public string Detalle { get; set; }

    public bool? EsInformativo { get; set; }

    public string Audiencia { get; set; }

    public int? Orden { get; set; }

    public bool? EsActivo { get; set; }
}