// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class CronCronograma
{
    public int IdCronograma { get; set; }

    public string IdPeriodo { get; set; }

    public string Detalle { get; set; }

    public bool? EsPublico { get; set; }

    public bool? EsActivo { get; set; }
}