// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Cuentas
{
    public int IdCuenta { get; set; }

    public string Cuenta { get; set; }

    public string NumeroCuenta { get; set; }

    public bool Activo { get; set; }

    public byte Esingreso { get; set; }

    public string TipoPago { get; set; }
}