// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Cursos
{
    public int IdNivel { get; set; }

    public int IdCarrera { get; set; }

    public string Nivel { get; set; }

    public int? Jerarquia { get; set; }

    public int? Orden { get; set; }

    public bool? EsRecuperacion { get; set; }

    public string AliasCurso { get; set; }

    public virtual ICollection<Detallemallas> Detallemallas { get; set; } = new List<Detallemallas>();

    public virtual Carreras IdCarreraNavigation { get; set; }

    public virtual ICollection<Matriculas> Matriculas { get; set; } = new List<Matriculas>();

    public virtual ICollection<Solicitudescalificaciones> Solicitudescalificaciones { get; set; } = new List<Solicitudescalificaciones>();
}