// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class DedicacionCategorias
{
    public int IdDedicacionCategorias { get; set; }

    public int IdDedicacion { get; set; }

    public int IdEscalafon { get; set; }

    public int? HorasMinimas { get; set; }

    public int? HorasMaximas { get; set; }

    public bool? EsActivo { get; set; }

    public virtual ICollection<Contratos> Contratos { get; set; } = new List<Contratos>();

    public virtual Dedicacion IdDedicacionNavigation { get; set; }

    public virtual Escalafon IdEscalafonNavigation { get; set; }

    public virtual ICollection<ProfesoresDedicacion> ProfesoresDedicacion { get; set; } = new List<ProfesoresDedicacion>();
}