// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Dedicacion
{
    public int IdDedicacion { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<DedicacionCategorias> DedicacionCategorias { get; set; } = new List<DedicacionCategorias>();

    public virtual ICollection<HorasAcademicas> HorasAcademicas { get; set; } = new List<HorasAcademicas>();

    public virtual ICollection<PlantillaContrato> PlantillaContrato { get; set; } = new List<PlantillaContrato>();
}