// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Departamentossolicitudes
{
    public int IdDepartamentoSolicitud { get; set; }

    public string Departamento { get; set; }

    public bool? Activo { get; set; }

    public virtual ICollection<Tipossolicitudes> Tipossolicitudes { get; set; } = new List<Tipossolicitudes>();
}