// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Departamentos
{
    public int Iddepartamentos { get; set; }

    public string NombreDepartamento { get; set; }

    public string Abreviacion { get; set; }

    public string Descripcion { get; set; }

    public int? IdInstitucion { get; set; }

    public virtual ICollection<OfertasLaborales> OfertasLaborales { get; set; } = new List<OfertasLaborales>();
}