// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class DetallePagos
{
    public int IdPago { get; set; }

    public int IdEspecie { get; set; }

    public decimal? Valor { get; set; }

    public decimal? Descuento { get; set; }

    public int? IdCredito { get; set; }

    public bool? MigradoContabilidad { get; set; }

    public DateTime? FechaMigracion { get; set; }

    public virtual Especies IdEspecieNavigation { get; set; }

    public virtual Pagos IdPagoNavigation { get; set; }
}