// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Detallemallas
{
    public int IdDetalleMalla { get; set; }

    public int IdMalla { get; set; }

    public int IdAsignatura { get; set; }

    public int IdNivel { get; set; }

    public int IdtipoAsignatura { get; set; }

    public string Tipo { get; set; }

    public bool? Opcional { get; set; }

    public int? Creditos { get; set; }

    public int? Horas { get; set; }

    public bool? Anulada { get; set; }

    public int? HorasDocente { get; set; }

    public decimal? HorasPracticoExperimental { get; set; }

    public virtual Asignaturas IdAsignaturaNavigation { get; set; }

    public virtual Mallas IdMallaNavigation { get; set; }

    public virtual Cursos IdNivelNavigation { get; set; }

    public virtual TiposAsignatura IdtipoAsignaturaNavigation { get; set; }

    public virtual ICollection<Prerequisitos> Prerequisitos { get; set; } = new List<Prerequisitos>();
}