// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class DetallesOfertas
{
    public int IddetallesOfertas { get; set; }

    public int IdofertasLaborales { get; set; }

    public int IdjornadasOfertas { get; set; }

    public int IdmodalidadesOfertas { get; set; }

    public virtual JornadasOfertas IdjornadasOfertasNavigation { get; set; }

    public virtual ModalidadesOfertas IdmodalidadesOfertasNavigation { get; set; }

    public virtual OfertasLaborales IdofertasLaboralesNavigation { get; set; }
}