// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class DetallesDocumentosPagos
{
    public uint Iddocumentopago { get; set; }

    public int Idpago { get; set; }

    public decimal Valor { get; set; }

    public virtual Pagos IdpagoNavigation { get; set; }
}