// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class DetalleSistemaEvaluacion
{
    public string Idperiodo { get; set; }

    public int Idcarrera { get; set; }

    public int Idsistemaevaluacion { get; set; }
}