// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Discapacidades
{
    public int IdDiscapacidad { get; set; }

    public string Discapacidad { get; set; }

    public bool? EsDefecto { get; set; }

    public virtual ICollection<Profesores> Profesores { get; set; } = new List<Profesores>();
}