// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class DocumentosAdjuntos
{
    public int IddocumentosAdjuntos { get; set; }

    public string IdAlumno { get; set; }

    public int IdtiposDocumentos { get; set; }

    public string NombreArchivo { get; set; }

    public string RutaArchivo { get; set; }

    public DateTime? FechaSubida { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public virtual TiposDocumentos IdtiposDocumentosNavigation { get; set; }

    public virtual ICollection<Postulaciones> Postulaciones { get; set; } = new List<Postulaciones>();
}