// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class EdEncuestas
{
    public int IdEncuesta { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public bool? Activo { get; set; }
}