// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class EdPreguntas
{
    public int IdPregunta { get; set; }

    public int? IdEncuesta { get; set; }

    public string Pregunta { get; set; }

    public int? Orden { get; set; }

    public bool? Activa { get; set; }

    public bool? EsAbierta { get; set; }
}