// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Empresas
{
    public string Idempresa { get; set; }

    public string TipoDocumento { get; set; }

    public int IdsectoresEmpresas { get; set; }

    public string NombreEmpresa { get; set; }

    public string PaisEmpresa { get; set; }

    public string CiudadEmpresa { get; set; }

    public string DireccionEmpresa { get; set; }

    public string TelefonoEmpresa { get; set; }

    public string EmailEmpresa { get; set; }

    public string UserEmpresa { get; set; }

    public string Password { get; set; }

    public DateTime? FechaInscripcion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public string EstadoVerificacion { get; set; }

    public DateOnly? FechaVerificacion { get; set; }

    public string ComentarioVerificacion { get; set; }

    public bool? EsActivo { get; set; }

    public virtual ICollection<EmpresasContactos> EmpresasContactos { get; set; } = new List<EmpresasContactos>();

    public virtual SectoresEmpresas IdsectoresEmpresasNavigation { get; set; }

    public virtual ICollection<OfertasLaborales> OfertasLaborales { get; set; } = new List<OfertasLaborales>();
}