// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class EmpresasContactos
{
    public int IdempresasContactos { get; set; }

    public string Idempresa { get; set; }

    public int IdtipoContacto { get; set; }

    public string Valor { get; set; }

    public DateOnly? FechaCreacion { get; set; }

    public DateOnly? FechaModificacion { get; set; }

    public virtual Empresas IdempresaNavigation { get; set; }

    public virtual TipoContacto IdtipoContactoNavigation { get; set; }
}