// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Escalafon
{
    public int IdEscalafon { get; set; }

    public int IdCategoriaContratos { get; set; }

    public string Nombre { get; set; }

    public bool? EsActivo { get; set; }

    public virtual ICollection<DedicacionCategorias> DedicacionCategorias { get; set; } = new List<DedicacionCategorias>();

    public virtual CategoriaContratos IdCategoriaContratosNavigation { get; set; }
}