// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Espacios
{
    public int IdEspacio { get; set; }

    public string Codigo { get; set; }

    public string Nombre { get; set; }

    public string Tipo { get; set; }

    public int Capacidad { get; set; }

    public int? IdCarrera { get; set; }

    public string Edificio { get; set; }

    public int Piso { get; set; }

    public bool Activo { get; set; }

    public bool? RequiereReserva { get; set; }

    public string ImagenReferencia { get; set; }

    public bool EsAsincrono { get; set; }

    public virtual ICollection<HorarioDetalle> HorarioDetalle { get; set; } = new List<HorarioDetalle>();

    public virtual Carreras IdCarreraNavigation { get; set; }
}