// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Especies
{
    public int IdEspecie { get; set; }

    public string Especie { get; set; }

    public decimal Valor { get; set; }

    public int NumeroCuotas { get; set; }

    public int? Prioridad { get; set; }

    public bool? PermiteIntercalar { get; set; }

    public string CodigoReferencia { get; set; }

    public string Idperiodo { get; set; }

    public decimal? Extraordinaria { get; set; }

    public int? IdNivel { get; set; }

    public virtual ICollection<DetallePagos> DetallePagos { get; set; } = new List<DetallePagos>();
}