// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class EspeciesExtras
{
    public int Idmatricula { get; set; }

    public int Idespecie { get; set; }

    public DateOnly FechaRegistro { get; set; }

    public decimal Valor { get; set; }

    public DateOnly FechaLimitePago { get; set; }

    public string Observacion { get; set; }

    public bool Obligatoria { get; set; }

    public decimal Pagado { get; set; }

    public bool Extra { get; set; }

    public string Tipo { get; set; }
}