// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Etnias
{
    public int IdEtnia { get; set; }

    public string Etnia { get; set; }

    public bool? EsIndigena { get; set; }

    public bool? NoRegistra { get; set; }

    public virtual ICollection<Alumnos> Alumnos { get; set; } = new List<Alumnos>();

    public virtual ICollection<Profesores> Profesores { get; set; } = new List<Profesores>();
}