// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class ExtrasContratos
{
    public int IdExtraContratos { get; set; }

    public int IdContratos { get; set; }

    public DateOnly? FechaRegistro { get; set; }

    public DateOnly? FechaInicioextra { get; set; }

    public decimal? ValorExtra { get; set; }

    public string Motivo { get; set; }

    public DateOnly? FechaFinalizacion { get; set; }

    public bool? Esactivo { get; set; }

    public string UsuarioRegistra { get; set; }

    public virtual Contratos IdContratosNavigation { get; set; }
}