// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class FechasHorarios
{
    public int IdFecha { get; set; }

    public DateOnly? Fecha { get; set; }

    public bool? Finsemana { get; set; }

    public string Dia { get; set; }

    public virtual ICollection<HorarioDetalle> HorarioDetalle { get; set; } = new List<HorarioDetalle>();

    public virtual ICollection<AcadSesiones> AcadSesiones { get; set; } = new List<AcadSesiones>();
}