// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class FechasPagos
{
    public int IdFecha { get; set; }

    public int? IdEspecie { get; set; }

    public DateOnly? Fecha { get; set; }
}