// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class FechasGrados
{
    public string Idperiodo { get; set; }

    public int Idnivel { get; set; }

    public int Idseccion { get; set; }

    public string Paralelo { get; set; }

    public DateOnly? FechaGrado { get; set; }
}