// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class FechasSemanas
{
    public int IdFechasSemanas { get; set; }

    public int IdSemanasHorarios { get; set; }

    public int IdFecha { get; set; }

    public string IdPeriodo { get; set; }
}