// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class FechasPagosCuotas
{
    public int IdFecha { get; set; }

    public string IdPeriodo { get; set; }

    public int IdModalidad { get; set; }

    public int IdCarrera { get; set; }

    public string CodigoReferencia { get; set; }

    public DateOnly? Fecha { get; set; }

    public decimal? ValorCuota { get; set; }

    public bool? GeneraFecha { get; set; }

    public bool? Activo { get; set; }

    public virtual Carreras IdCarreraNavigation { get; set; }

    public virtual Modalidades IdModalidadNavigation { get; set; }

    public virtual Periodos IdPeriodoNavigation { get; set; }
}