// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class GestPasswordResets
{
    public int IdToken { get; set; }

    public int IdUsuario { get; set; }

    public string TokenHash { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime FechaExpiracion { get; set; }

    public bool Usado { get; set; }

    public string IpSolicitud { get; set; }

    public virtual Usuarios IdUsuarioNavigation { get; set; }
}