// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class GradosAcademicos
{
    public int IdGradoAcademico { get; set; }

    public int IdNivelAcademico { get; set; }

    public string Nombre { get; set; }

    public virtual NivelesAcademicos IdNivelAcademicoNavigation { get; set; }

    public virtual ICollection<TitulosEnCurso> TitulosEnCurso { get; set; } = new List<TitulosEnCurso>();

    public virtual ICollection<TitulosProfesores> TitulosProfesores { get; set; } = new List<TitulosProfesores>();
}