// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Habilidades
{
    public int Idhabilidades { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<AlumnosHabilidades> AlumnosHabilidades { get; set; } = new List<AlumnosHabilidades>();

    public virtual ICollection<HabilidadesRequeridas> HabilidadesRequeridas { get; set; } = new List<HabilidadesRequeridas>();
}