// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class HabilidadesRequeridas
{
    public int IdhabilidadesRequeridas { get; set; }

    public int IdofertasLaborales { get; set; }

    public int Idhabilidades { get; set; }

    public string Nivel { get; set; }

    public bool? EsObligatoria { get; set; }

    public virtual Habilidades IdhabilidadesNavigation { get; set; }

    public virtual OfertasLaborales IdofertasLaboralesNavigation { get; set; }
}