// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class HdvEnlacesMagicos
{
    public int IdHdvEnlacesMagicos { get; set; }

    public string IdProfesor { get; set; }

    public string Token { get; set; }

    public DateTime FechaExpiracion { get; set; }

    /// <summary>
    /// Pendiente, Utilizado, Expirado
    /// </summary>
    public string Estado { get; set; }

    public virtual ICollection<HdvSolicitudesActualizacion> HdvSolicitudesActualizacion { get; set; } = new List<HdvSolicitudesActualizacion>();
}