// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class HdvSolicitudesActualizacion
{
    public int IdHdvSolicitudesActualizacion { get; set; }

    public string IdProfesor { get; set; }

    public int IdHdvEnlacesMagicos { get; set; }

    public string DatosPropuestos { get; set; }

    public string RutaArchivosAdjuntos { get; set; }

    /// <summary>
    /// Pendiente, Aprobado, Rechazado
    /// 
    /// </summary>
    public string Estado { get; set; }

    public DateTime FechaSolicitud { get; set; }

    public int? RevisadoPor { get; set; }

    public DateTime? FechaRevision { get; set; }

    public virtual HdvEnlacesMagicos IdHdvEnlacesMagicosNavigation { get; set; }
}