// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class HorarioDetalle
{
    public int IdHorario { get; set; }

    public int IdAsignacion { get; set; }

    public int IdFecha { get; set; }

    public int Idhora { get; set; }

    public int? IdEspacio { get; set; }

    public string TipoBloque { get; set; }

    public bool? Activo { get; set; }

    public bool? ClaseReasignacion { get; set; }

    public bool? EsRecuperacionPedagocia { get; set; }

    public string Observacion { get; set; }

    public int? IdHorarioReasgincacion { get; set; }

    public virtual AsignacionesProfesores IdAsignacionNavigation { get; set; }

    public virtual Espacios IdEspacioNavigation { get; set; }

    public virtual FechasHorarios IdFechaNavigation { get; set; }

    public virtual HorasClases IdhoraNavigation { get; set; }
}