// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class HorarioProfesores
{
    public int IdHorario { get; set; }

    public int? IdAsignacion { get; set; }

    public int? IdHora { get; set; }

    public int? IdFecha { get; set; }

    public bool? Asiste { get; set; }

    public bool? Activo { get; set; }
}