// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Instituciones
{
    public int IdInstitucion { get; set; }

    public string Institucion { get; set; }

    public string Ciudad { get; set; }

    public string Provincia { get; set; }
}