// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class InstitucionesInstituto
{
    public int IdInstitucionesInstituto { get; set; }

    public string Nombre { get; set; }

    public string Ruc { get; set; }

    public string Ubicado { get; set; }

    public string Representante { get; set; }

    public string CedulaRepresentante { get; set; }

    public virtual ICollection<Contratos> Contratos { get; set; } = new List<Contratos>();

    public virtual ICollection<PlantillaContrato> PlantillaContrato { get; set; } = new List<PlantillaContrato>();
}