// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Logsmigraciones
{
    public int IdLog { get; set; }

    public string Status { get; set; }

    public DateTime? Fecha { get; set; }
}