// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class MallasPeriodos
{
    public string IdPeriodo { get; set; }

    public int IdNivel { get; set; }

    public int IdMalla { get; set; }
}