// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Mallas
{
    public int IdMalla { get; set; }

    public int IdCarrera { get; set; }

    public int? Vigencia { get; set; }

    public string Descripcion { get; set; }

    public int? CreditosMinimo { get; set; }

    public int? CreditosMaximo { get; set; }

    public int? CreditosReprobatorio { get; set; }

    public bool? Activa { get; set; }

    public virtual ICollection<Cambiosmalla> Cambiosmalla { get; set; } = new List<Cambiosmalla>();

    public virtual ICollection<Detallemallas> Detallemallas { get; set; } = new List<Detallemallas>();

    public virtual Carreras IdCarreraNavigation { get; set; }
}