// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Matriculas
{
    public int IdMatricula { get; set; }

    public string IdAlumno { get; set; }

    public int IdNivel { get; set; }

    public int IdSeccion { get; set; }

    public int IdModalidad { get; set; }

    public string IdPeriodo { get; set; }

    public DateTime? FechaMatricula { get; set; }

    public string Paralelo { get; set; }

    public bool? Arrastres { get; set; }

    public int? Folio { get; set; }

    public decimal? BecaMatricula { get; set; }

    public decimal? BecaColegiatura { get; set; }

    public bool? Retirado { get; set; }

    public DateOnly? FechaRetiro { get; set; }

    public string Observacion { get; set; }

    public bool? Convalidacion { get; set; }

    public string CarreraConvalidada { get; set; }

    public int? NumeroPermiso { get; set; }

    public string UserMatricula { get; set; }

    public bool? Valida { get; set; }

    public bool? EsOyente { get; set; }

    public string DocumentoFactura { get; set; }

    public virtual ICollection<BienApoyoFinanciero> BienApoyoFinanciero { get; set; } = new List<BienApoyoFinanciero>();

    public virtual ICollection<BienPermisosSalidasAlumnos> BienPermisosSalidasAlumnos { get; set; } = new List<BienPermisosSalidasAlumnos>();

    public virtual ICollection<BienPostulacionesBecas> BienPostulacionesBecas { get; set; } = new List<BienPostulacionesBecas>();

    public virtual ICollection<Calificaciones> Calificaciones { get; set; } = new List<Calificaciones>();

    public virtual Alumnos IdAlumnoNavigation { get; set; }

    public virtual Modalidades IdModalidadNavigation { get; set; }

    public virtual Cursos IdNivelNavigation { get; set; }

    public virtual Periodos IdPeriodoNavigation { get; set; }

    public virtual Secciones IdSeccionNavigation { get; set; }

    public virtual ICollection<Solicitudescalificaciones> Solicitudescalificaciones { get; set; } = new List<Solicitudescalificaciones>();

    public virtual ICollection<TitulPostulacionAlumnos> TitulPostulacionAlumnos { get; set; } = new List<TitulPostulacionAlumnos>();

    public virtual ICollection<Vinculacionproyectosalumnos> Vinculacionproyectosalumnos { get; set; } = new List<Vinculacionproyectosalumnos>();

    public virtual ICollection<AcadAsistencias> AcadAsistencias { get; set; } = new List<AcadAsistencias>();
}