// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class MediosContacto
{
    public int IdMedio { get; set; }

    public string Medio { get; set; }

    public ulong? Activo { get; set; }
}