// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class ModalidadesOfertas
{
    public int IdmodalidadesOfertas { get; set; }

    public string TipoModalidad { get; set; }

    public virtual ICollection<DetallesOfertas> DetallesOfertas { get; set; } = new List<DetallesOfertas>();
}