// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Modalidades
{
    public int IdModalidad { get; set; }

    public string Modalidad { get; set; }

    public string Sufijo { get; set; }

    public string ModalidadImpresion { get; set; }

    public virtual ICollection<FechasPagosCuotas> FechasPagosCuotas { get; set; } = new List<FechasPagosCuotas>();

    public virtual ICollection<Matriculas> Matriculas { get; set; } = new List<Matriculas>();

    public virtual ICollection<ModalidadesCarreras> ModalidadesCarreras { get; set; } = new List<ModalidadesCarreras>();
}