// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class ModalidadesCarreras
{
    public int IdModalidadCarrera { get; set; }

    public int IdCarrera { get; set; }

    public int IdModalidad { get; set; }

    public bool? EsActivo { get; set; }

    public virtual Carreras IdCarreraNavigation { get; set; }

    public virtual Modalidades IdModalidadNavigation { get; set; }

    public virtual ICollection<TitulCohortesCarreras> TitulCohortesCarreras { get; set; } = new List<TitulCohortesCarreras>();
}