// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class MotivoSalida
{
    public int IdMotivoSalida { get; set; }

    public string NombreMotivo { get; set; }

    public bool? NecesitaInfrome { get; set; }

    public bool? Esactivo { get; set; }

    public virtual ICollection<ProfesoresMotivoSalida> ProfesoresMotivoSalida { get; set; } = new List<ProfesoresMotivoSalida>();
}