// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Nacionalidades
{
    public int IdNacionalidad { get; set; }

    public string Nacionalidad { get; set; }

    public bool? EsNinguna { get; set; }

    public virtual ICollection<Profesores> Profesores { get; set; } = new List<Profesores>();
}