// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class NivelesAcademicos
{
    public int IdNivelAcademico { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<GradosAcademicos> GradosAcademicos { get; set; } = new List<GradosAcademicos>();
}