// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class OfertasCarreras
{
    public int IdofertasCarreras { get; set; }

    public int IdofertasLaborales { get; set; }

    public int IdCarrera { get; set; }

    public virtual Carreras IdCarreraNavigation { get; set; }

    public virtual OfertasLaborales IdofertasLaboralesNavigation { get; set; }
}