// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class OfertasLaborales
{
    public int IdofertasLaborales { get; set; }

    public string Idempresa { get; set; }

    public int Iddepartamentos { get; set; }

    public int IdcargosOfertas { get; set; }

    public string Provincia { get; set; }

    public string Ciudad { get; set; }

    public string Ubicacion { get; set; }

    public int IdtiposOfertas { get; set; }

    public string ExperienciaRequerida { get; set; }

    public int? Vacantes { get; set; }

    public string Estado { get; set; }

    public DateTime? FechaPublicacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public DateTime? FechaCierre { get; set; }

    public decimal? Salario { get; set; }

    public string EnlaceOriginal { get; set; }

    public bool? EsActivo { get; set; }

    public virtual ICollection<DetallesOfertas> DetallesOfertas { get; set; } = new List<DetallesOfertas>();

    public virtual ICollection<HabilidadesRequeridas> HabilidadesRequeridas { get; set; } = new List<HabilidadesRequeridas>();

    public virtual CargosOfertas IdcargosOfertasNavigation { get; set; }

    public virtual Departamentos IddepartamentosNavigation { get; set; }

    public virtual Empresas IdempresaNavigation { get; set; }

    public virtual TiposOfertas IdtiposOfertasNavigation { get; set; }

    public virtual ICollection<OfertasCarreras> OfertasCarreras { get; set; } = new List<OfertasCarreras>();

    public virtual ICollection<OfertasRequisitos> OfertasRequisitos { get; set; } = new List<OfertasRequisitos>();

    public virtual ICollection<Postulaciones> Postulaciones { get; set; } = new List<Postulaciones>();
}