// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class OfertasRequisitos
{
    public int IdofertasRequisitos { get; set; }

    public int IdofertasLaborales { get; set; }

    public string Descripcion { get; set; }

    public bool? EsObligatoria { get; set; }

    public virtual OfertasLaborales IdofertasLaboralesNavigation { get; set; }
}