// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Paises
{
    public int Idpaises { get; set; }

    public string Nombre { get; set; }

    public string Nacionalidad { get; set; }

    public bool? EsEcuador { get; set; }

    public virtual ICollection<BienParentezcosAlumno> BienParentezcosAlumno { get; set; } = new List<BienParentezcosAlumno>();

    public virtual ICollection<Provincias> Provincias { get; set; } = new List<Provincias>();

    public virtual ICollection<Universidades> Universidades { get; set; } = new List<Universidades>();
}