// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Parciales
{
    public int IdParcial { get; set; }

    public string Parcial { get; set; }

    public DateOnly? FechaInicio { get; set; }

    public DateOnly? FechaFinal { get; set; }

    public bool? EsPrimero { get; set; }

    public bool? EsSegundo { get; set; }

    public bool? EsExamenFinal { get; set; }

    public bool? EsRemedial { get; set; }

    public virtual ICollection<Solicitudescalificaciones> Solicitudescalificaciones { get; set; } = new List<Solicitudescalificaciones>();
}