// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Periodos
{
    public string IdPeriodo { get; set; }

    public string Detalle { get; set; }

    public DateOnly? FechaInicial { get; set; }

    public DateOnly? FechaFinal { get; set; }

    public bool? Cerrado { get; set; }

    public DateOnly? FechaMaximaAutocierre { get; set; }

    public bool? Activo { get; set; }

    public bool? Creditos { get; set; }

    public uint? NumeroPagos { get; set; }

    public DateOnly? FechaMatruclaExtraordinaria { get; set; }

    public int? Foliop { get; set; }

    public bool? PermiteMatricula { get; set; }

    public bool? IngresoCalificaciones { get; set; }

    public bool? PermiteCalificacionesInstituto { get; set; }

    public bool? Periodoactivoinstituto { get; set; }

    public bool? VisualizaPowerBi { get; set; }

    public bool? EsInstituto { get; set; }

    public bool? PeriodoPlanificacion { get; set; }

    public bool? EsConduccion { get; set; }

    public virtual ICollection<BienCaso> BienCaso { get; set; } = new List<BienCaso>();

    public virtual ICollection<BienFichaSocioeconomica> BienFichaSocioeconomica { get; set; } = new List<BienFichaSocioeconomica>();

    public virtual ICollection<BienResolucionesTribunales> BienResolucionesTribunales { get; set; } = new List<BienResolucionesTribunales>();

    public virtual ICollection<ContratosAsignaturas> ContratosAsignaturas { get; set; } = new List<ContratosAsignaturas>();

    public virtual ICollection<FechasPagosCuotas> FechasPagosCuotas { get; set; } = new List<FechasPagosCuotas>();

    public virtual ICollection<Matriculas> Matriculas { get; set; } = new List<Matriculas>();

    public virtual ICollection<ProfesoresCarrerasPeriodos> ProfesoresCarrerasPeriodos { get; set; } = new List<ProfesoresCarrerasPeriodos>();

    public virtual ICollection<ProfesoresDedicacion> ProfesoresDedicacion { get; set; } = new List<ProfesoresDedicacion>();

    public virtual ICollection<TitulCohortes> TitulCohortes { get; set; } = new List<TitulCohortes>();
}