// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class PlantillaClausulas
{
    public int IdPlantillasClausulas { get; set; }

    public int IdPlantillaContrato { get; set; }

    public int IdClausulas { get; set; }

    public string Texto { get; set; }

    public int? Orden { get; set; }

    public DateOnly? FechaCreacion { get; set; }

    public DateOnly? FechaModificacion { get; set; }

    public bool? EsActivo { get; set; }

    public virtual Clausulas IdClausulasNavigation { get; set; }

    public virtual PlantillaContrato IdPlantillaContratoNavigation { get; set; }
}