// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Plantillas
{
    public int IdPlantilla { get; set; }

    public DateTime? FechaRegistro { get; set; }

    public string Nombre { get; set; }

    public string Archivo { get; set; }

    public string Usuario { get; set; }

    public bool? Activo { get; set; }

    public virtual ICollection<Plantillasparametros> Plantillasparametros { get; set; } = new List<Plantillasparametros>();
}