// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class PlantillaContrato
{
    public int IdPlantillaContrato { get; set; }

    public int IdDedicacion { get; set; }

    public int IdTiposContratos { get; set; }

    public int IdInstitucionesInstituto { get; set; }

    public int IdSello { get; set; }

    public int IdFondo { get; set; }

    public string Titulo { get; set; }

    public string Cuerpo { get; set; }

    public int? Version { get; set; }

    public DateOnly? FechaCreacion { get; set; }

    public DateOnly? FechaModificacion { get; set; }

    public bool? EsActivo { get; set; }

    public bool? EsDocente { get; set; }

    public virtual Dedicacion IdDedicacionNavigation { get; set; }

    public virtual AdjuntosImagenes IdFondoNavigation { get; set; }

    public virtual InstitucionesInstituto IdInstitucionesInstitutoNavigation { get; set; }

    public virtual AdjuntosImagenes IdSelloNavigation { get; set; }

    public virtual TiposContratos IdTiposContratosNavigation { get; set; }

    public virtual ICollection<PlantillaClausulas> PlantillaClausulas { get; set; } = new List<PlantillaClausulas>();
}