// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Postulaciones
{
    public int IdPostulaciones { get; set; }

    public int IdofertasLaborales { get; set; }

    public string IdAlumno { get; set; }

    public int IddocumentosAdjuntos { get; set; }

    public DateTime? FechaPostulacion { get; set; }

    public string Estado { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public virtual DocumentosAdjuntos IddocumentosAdjuntosNavigation { get; set; }

    public virtual OfertasLaborales IdofertasLaboralesNavigation { get; set; }
}