// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Prerequisitos
{
    public int IdDetalleMalla { get; set; }

    public int IdAsignatura { get; set; }

    public bool? Activa { get; set; }

    public virtual Asignaturas IdAsignaturaNavigation { get; set; }

    public virtual Detallemallas IdDetalleMallaNavigation { get; set; }
}