// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class ProfesoresActividades
{
    public string IdPeriodo { get; set; }

    public string IdProfesor { get; set; }

    public int IdSubcategoria { get; set; }

    public int? HorasSemana { get; set; }

    public string Usuario { get; set; }

    public DateTime? Fecha { get; set; }

    public virtual SubcategoriasActividades IdSubcategoriaNavigation { get; set; }
}