// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Profesores
{
    public string IdProfesor { get; set; }

    public string Tipodocumento { get; set; }

    public string Apellidos { get; set; }

    public string Nombres { get; set; }

    public string PrimerApellido { get; set; }

    public string SegundoApellido { get; set; }

    public string PrimerNombre { get; set; }

    public string SegundoNombre { get; set; }

    public int EstadoCivil { get; set; }

    public string Direccion { get; set; }

    public string CallePrincipal { get; set; }

    public string CalleSecundaria { get; set; }

    public string NumeroCasa { get; set; }

    public string Telefono { get; set; }

    public string Celular { get; set; }

    public string Email { get; set; }

    public DateOnly? FechaNacimiento { get; set; }

    public string Sexo { get; set; }

    public string Clave { get; set; }

    public bool? Practicas { get; set; }

    public string Tipo { get; set; }

    public string Nacionalidad { get; set; }

    public string Titulo { get; set; }

    public string Abreviatura { get; set; }

    public string AbreviaturaPost { get; set; }

    public bool? Activo { get; set; }

    public int IdEtnia { get; set; }

    public int IdNacionalidad { get; set; }

    public int IdParroquiaNacimiento { get; set; }

    public string EmailInstitucional { get; set; }

    public DateOnly? FechaIngreso { get; set; }

    public DateOnly? FechaIngresoIess { get; set; }

    public DateOnly? FechaRetiro { get; set; }

    public int IdParroquiaResidencia { get; set; }

    public string TipoSangre { get; set; }

    public string CodigoPostal { get; set; }

    public int IdDiscapacidad { get; set; }

    public int? PorcentajeDiscapacidad { get; set; }

    public string NumeroConadis { get; set; }

    public string Foto { get; set; }

    public bool? EsReal { get; set; }

    public virtual ICollection<CertificadosExperienciaLaboral> CertificadosExperienciaLaboral { get; set; } = new List<CertificadosExperienciaLaboral>();

    public virtual ICollection<Contratos> Contratos { get; set; } = new List<Contratos>();

    public virtual ICollection<CursosProfesores> CursosProfesores { get; set; } = new List<CursosProfesores>();

    public virtual Estadocivil EstadoCivilNavigation { get; set; }

    public virtual Discapacidades IdDiscapacidadNavigation { get; set; }

    public virtual Etnias IdEtniaNavigation { get; set; }

    public virtual Nacionalidades IdNacionalidadNavigation { get; set; }

    public virtual Parroquias IdParroquiaNacimientoNavigation { get; set; }

    public virtual Parroquias IdParroquiaResidenciaNavigation { get; set; }

    public virtual ICollection<KardexVacaciones> KardexVacaciones { get; set; } = new List<KardexVacaciones>();

    public virtual ICollection<ProfesoresCarrerasPeriodos> ProfesoresCarrerasPeriodos { get; set; } = new List<ProfesoresCarrerasPeriodos>();

    public virtual ICollection<ProfesoresDedicacion> ProfesoresDedicacion { get; set; } = new List<ProfesoresDedicacion>();

    public virtual ICollection<ProfesoresHistorialLaboral> ProfesoresHistorialLaboral { get; set; } = new List<ProfesoresHistorialLaboral>();

    public virtual ICollection<ProfesoresMotivoSalida> ProfesoresMotivoSalida { get; set; } = new List<ProfesoresMotivoSalida>();

    public virtual ICollection<SolicitudesLicencias> SolicitudesLicencias { get; set; } = new List<SolicitudesLicencias>();

    public virtual Tiposangre TipoSangreNavigation { get; set; }

    public virtual ICollection<TitulosEnCurso> TitulosEnCurso { get; set; } = new List<TitulosEnCurso>();

    public virtual ICollection<TitulosProfesores> TitulosProfesores { get; set; } = new List<TitulosProfesores>();

    public virtual ICollection<TitulResponsableRequisitos> TitulResponsableRequisitos { get; set; } = new List<TitulResponsableRequisitos>();

    public virtual ICollection<VacConfigDiasExtrasExcepciones> VacConfigDiasExtrasExcepciones { get; set; } = new List<VacConfigDiasExtrasExcepciones>();
}