// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class ProfesoresMotivoSalida
{
    public string IdProfesor { get; set; }

    public int IdMotivoSalida { get; set; }

    public int IdContratos { get; set; }

    public string Observacion { get; set; }

    public string RutaArchivo { get; set; }

    public DateOnly? FechaRegistro { get; set; }

    public DateOnly? FechaSalida { get; set; }

    public virtual Contratos IdContratosNavigation { get; set; }

    public virtual MotivoSalida IdMotivoSalidaNavigation { get; set; }

    public virtual Profesores IdProfesorNavigation { get; set; }
}