// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class ProfesoresCarrerasPeriodos
{
    public int IdProfesoresCarrerasPeriodos { get; set; }

    public string IdPeriodo { get; set; }

    public string IdProfesor { get; set; }

    public int? IdCarrera { get; set; }

    public bool? EsActivo { get; set; }

    public bool? SonTodas { get; set; }

    public virtual Carreras IdCarreraNavigation { get; set; }

    public virtual Periodos IdPeriodoNavigation { get; set; }

    public virtual Profesores IdProfesorNavigation { get; set; }
}