// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Provincias
{
    public int Idprovincias { get; set; }

    public int Idpaises { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<Ciudades> Ciudades { get; set; } = new List<Ciudades>();

    public virtual Paises IdpaisesNavigation { get; set; }
}