// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class RbacModulos
{
    public int IdModulos { get; set; }

    public int IdSistema { get; set; }

    public string Nombre { get; set; }

    public bool? EsActivo { get; set; }

    public virtual RbacSistema IdSistemaNavigation { get; set; }

    public virtual ICollection<RbacModulosOperaciones> RbacModulosOperaciones { get; set; } = new List<RbacModulosOperaciones>();
}