// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class RbacSistema
{
    public int IdSistema { get; set; }

    public string Codigo { get; set; }

    public string Detalle { get; set; }

    public string Url { get; set; }

    public string Icono { get; set; }

    public virtual ICollection<RbacModulos> RbacModulos { get; set; } = new List<RbacModulos>();
}