// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class RbacModulosOperaciones
{
    public int IdModulosOperaciones { get; set; }

    public int IdModulos { get; set; }

    public int IdOperaciones { get; set; }

    public DateOnly? FechaCreacion { get; set; }

    public DateOnly? FechaModificacion { get; set; }

    public bool? EsActivo { get; set; }

    public virtual RbacModulos IdModulosNavigation { get; set; }

    public virtual RbacOperaciones IdOperacionesNavigation { get; set; }

    public virtual ICollection<RbacRolModuloOperacion> RbacRolModuloOperacion { get; set; } = new List<RbacRolModuloOperacion>();
}