// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class RbacOperaciones
{
    public int IdOperaciones { get; set; }

    public string NombreOperacion { get; set; }

    public virtual ICollection<RbacModulosOperaciones> RbacModulosOperaciones { get; set; } = new List<RbacModulosOperaciones>();
}