// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class RbacRol
{
    public int IdRol { get; set; }

    public string Nombre { get; set; }

    public string CodigoRol { get; set; }

    public bool? EsActivo { get; set; }

    public virtual ICollection<RbacRolModuloOperacion> RbacRolModuloOperacion { get; set; } = new List<RbacRolModuloOperacion>();

    public virtual ICollection<RbacUsuarioRol> RbacUsuarioRol { get; set; } = new List<RbacUsuarioRol>();
}