// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Respuestassolicitudes
{
    public int IdRespuestaSolicitud { get; set; }

    public int? IdSolicitud { get; set; }

    public int? IdEstadoSolicitud { get; set; }

    public int? IdUsuarioSolicitud { get; set; }

    public DateTime? FechaRegistro { get; set; }

    public string DetalleRespuesta { get; set; }

    public bool? AdjuntaArchivo { get; set; }

    public string MailRespuesta { get; set; }

    public bool? EnvioMail { get; set; }

    public DateTime? FechaRespuesta { get; set; }

    public bool? Activo { get; set; }

    public string ArchivoAjunto { get; set; }

    public bool? RevisarLogs { get; set; }

    public bool? AdjuntarSoloArchivoAdjunto { get; set; }
}