// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Restricciones
{
    public string Idrestriccion { get; set; }

    public string Restriccion { get; set; }

    public ulong? Activo { get; set; }
}