// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Secciones
{
    public int IdSeccion { get; set; }

    public string Seccion { get; set; }

    public string Sufijo { get; set; }

    public virtual ICollection<Matriculas> Matriculas { get; set; } = new List<Matriculas>();
}