// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class SectoresEmpresas
{
    public int IdsectoresEmpresas { get; set; }

    public string NombreSector { get; set; }

    public string CodigoSector { get; set; }

    public virtual ICollection<Empresas> Empresas { get; set; } = new List<Empresas>();
}