// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Seddautoridadescarrerasperiodos
{
    public int IdAsignacion { get; set; }

    public int? IdCarrera { get; set; }

    public string IdPeriodo { get; set; }

    public string IdProfesor { get; set; }

    public int? IdInstrumento { get; set; }

    public string Designacion { get; set; }

    public bool? Activo { get; set; }
}