// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Seddinstrumentospreguntas
{
    public int IdInstrumentoPregunta { get; set; }

    public int? IdInstrumento { get; set; }

    public int? IdPregunta { get; set; }

    public DateTime FechaRegistro { get; set; }

    public bool? Activo { get; set; }

    public virtual Seddinstrumentos IdInstrumentoNavigation { get; set; }

    public virtual Seddpreguntas IdPreguntaNavigation { get; set; }
}