// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Sedddetalleautoevaluacion
{
    public int IdDetalle { get; set; }

    public int? IdTest { get; set; }

    public int? IdPregunta { get; set; }

    public int? Respuesta { get; set; }

    public virtual Seddpreguntas IdPreguntaNavigation { get; set; }

    public virtual Seddautoevaluacion IdTestNavigation { get; set; }
}