// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Seddinstrumentos
{
    public int IdInstrumento { get; set; }

    public int? IdCategoria { get; set; }

    public string Instrumento { get; set; }

    public string Codigo { get; set; }

    public int? Porcentaje { get; set; }

    public bool? Activo { get; set; }

    public virtual CategoriasActividades IdCategoriaNavigation { get; set; }

    public virtual ICollection<Seddautoevaluacion> Seddautoevaluacion { get; set; } = new List<Seddautoevaluacion>();

    public virtual ICollection<Seddcoevaluacion> Seddcoevaluacion { get; set; } = new List<Seddcoevaluacion>();

    public virtual ICollection<Seddcoevaluacionautoridad> Seddcoevaluacionautoridad { get; set; } = new List<Seddcoevaluacionautoridad>();

    public virtual ICollection<Seddheteroevaluacion> Seddheteroevaluacion { get; set; } = new List<Seddheteroevaluacion>();

    public virtual ICollection<Seddinsitu> Seddinsitu { get; set; } = new List<Seddinsitu>();

    public virtual ICollection<Seddinstrumentospreguntas> Seddinstrumentospreguntas { get; set; } = new List<Seddinstrumentospreguntas>();
}