// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Seddpreguntas
{
    public int IdPregunta { get; set; }

    public string Pregunta { get; set; }

    public bool? Activo { get; set; }

    public virtual ICollection<Sedddetalleautoevaluacion> Sedddetalleautoevaluacion { get; set; } = new List<Sedddetalleautoevaluacion>();

    public virtual ICollection<Sedddetallecoevaluacion> Sedddetallecoevaluacion { get; set; } = new List<Sedddetallecoevaluacion>();

    public virtual ICollection<Sedddetallecoevaluacionautoridad> Sedddetallecoevaluacionautoridad { get; set; } = new List<Sedddetallecoevaluacionautoridad>();

    public virtual ICollection<Sedddetalleheteroevaluacion> Sedddetalleheteroevaluacion { get; set; } = new List<Sedddetalleheteroevaluacion>();

    public virtual ICollection<Seddinstrumentospreguntas> Seddinstrumentospreguntas { get; set; } = new List<Seddinstrumentospreguntas>();
}