// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Seddcoevaluacion
{
    public int IdTest { get; set; }

    public int? IdInstrumento { get; set; }

    public string IdPeriodo { get; set; }

    public int? IdAsignacion { get; set; }

    public string IdProfesor { get; set; }

    public DateTime? FechaRegistro { get; set; }

    public DateTime? FechaTest { get; set; }

    public virtual Seddinstrumentos IdInstrumentoNavigation { get; set; }

    public virtual ICollection<Sedddetallecoevaluacion> Sedddetallecoevaluacion { get; set; } = new List<Sedddetallecoevaluacion>();
}