// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class SemanasHorarios
{
    public int IdSemanasHorarios { get; set; }

    public string Detalle { get; set; }

    public bool? Activo { get; set; }

    public bool? EsExamen { get; set; }
}