// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Solicitudeslogs
{
    public int IdLogSolicitud { get; set; }

    public int? IdSolicitud { get; set; }

    public DateTime? FechaRegistro { get; set; }

    public string Detalle { get; set; }

    public int? IdRespuestaSolicitud { get; set; }
}