// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Solicitudescalificaciones
{
    public int IdSolicitudCalificacion { get; set; }

    public DateTime? FechaRegistro { get; set; }

    public DateTime? FechaHabilitado { get; set; }

    public int? IdSolicitud { get; set; }

    public int? IdParcial { get; set; }

    public int? IdMatricula { get; set; }

    public int? IdAsignatura { get; set; }

    public int? IdNivel { get; set; }

    public string IdPeriodo { get; set; }

    public string Paralelo { get; set; }

    public DateTime? FechaCalificacion { get; set; }

    public string IdProfesor { get; set; }

    public decimal? Calificacion { get; set; }

    public bool? Activo { get; set; }

    public virtual Asignaturas IdAsignaturaNavigation { get; set; }

    public virtual Matriculas IdMatriculaNavigation { get; set; }

    public virtual Cursos IdNivelNavigation { get; set; }

    public virtual Parciales IdParcialNavigation { get; set; }

    public virtual Solicitudes IdSolicitudNavigation { get; set; }
}