// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class SubcategoriasActividades
{
    public int IdSubcategoria { get; set; }

    public int? IdCategoria { get; set; }

    public string Subcategoria { get; set; }

    public bool? EsDocencia { get; set; }

    public bool? Activa { get; set; }

    public virtual CategoriasActividades IdCategoriaNavigation { get; set; }

    public virtual ICollection<ProfesoresActividades> ProfesoresActividades { get; set; } = new List<ProfesoresActividades>();
}