// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class SubcategoriaVehiculos
{
    public int IdSubcategoria { get; set; }

    public string Subcategoria { get; set; }

    public bool? Activa { get; set; }
}