// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class SueldosContratos
{
    public int IdSueldosContratos { get; set; }

    public int IdContratos { get; set; }

    public DateOnly? FechaRegistro { get; set; }

    public DateOnly? FechaCambiosueldo { get; set; }

    public decimal? Sueldo { get; set; }

    public bool? Esactivo { get; set; }

    public string UsarioRegistra { get; set; }

    public virtual Contratos IdContratosNavigation { get; set; }
}