// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class TipoContacto
{
    public int IdtipoContacto { get; set; }

    public string NombreContacto { get; set; }

    public string LongitudContacto { get; set; }

    public virtual ICollection<EmpresasContactos> EmpresasContactos { get; set; } = new List<EmpresasContactos>();
}