// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class TiposAsignatura
{
    public int IdtipoAsignatura { get; set; }

    public string TipoAsignatura { get; set; }

    public string Abreviatura { get; set; }

    public bool? Activo { get; set; }

    public bool? NoDefinida { get; set; }

    public virtual ICollection<Detallemallas> Detallemallas { get; set; } = new List<Detallemallas>();
}