// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class TiposDocumentos
{
    public int IdtiposDocumentos { get; set; }

    public string Documento { get; set; }

    public string SubijoDocumento { get; set; }

    public virtual ICollection<DocumentosAdjuntos> DocumentosAdjuntos { get; set; } = new List<DocumentosAdjuntos>();
}