// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Tipossolicitudes
{
    public int IdTipoSolicitud { get; set; }

    public int? IdCategoriaSolicitud { get; set; }

    public int? IdDepartamentoSolicitud { get; set; }

    public string TipoSolicitud { get; set; }

    public bool? Activo { get; set; }

    public bool? EscuelaConduccion { get; set; }

    public virtual Categoriassolicitudes IdCategoriaSolicitudNavigation { get; set; }

    public virtual Departamentossolicitudes IdDepartamentoSolicitudNavigation { get; set; }

    public virtual ICollection<Parametrostipossolicitudes> Parametrostipossolicitudes { get; set; } = new List<Parametrostipossolicitudes>();

    public virtual ICollection<Solicitudes> Solicitudes { get; set; } = new List<Solicitudes>();

    public virtual ICollection<Usuariosdepartamentossolicitudes> Usuariosdepartamentossolicitudes { get; set; } = new List<Usuariosdepartamentossolicitudes>();
}