// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class TiposContratos
{
    public int IdTiposContratos { get; set; }

    public string Nombre { get; set; }

    public string Codigo { get; set; }

    public int? DuracionSemanas { get; set; }

    public ulong? EsAfiliado { get; set; }

    public virtual ICollection<PlantillaContrato> PlantillaContrato { get; set; } = new List<PlantillaContrato>();
}