// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Tiposangre
{
    public string CodigoTipoSangre { get; set; }

    public string Grupo { get; set; }

    public bool? SitemaRh { get; set; }

    public virtual ICollection<Profesores> Profesores { get; set; } = new List<Profesores>();
}