// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class TipoFuncionario
{
    public int IdTipoFuncionario { get; set; }

    public string Nombre { get; set; }

    public ulong? EsDocente { get; set; }

    public virtual ICollection<CargoInstituto> CargoInstituto { get; set; } = new List<CargoInstituto>();
}