// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class TitulRequisitos
{
    public int IdRequisitos { get; set; }

    public string Requisito { get; set; }

    public bool? EsAdjunto { get; set; }

    public bool? EsBool { get; set; }

    public bool? SubeAlumno { get; set; }

    public bool? SubeColaborador { get; set; }

    public bool? EsActivo { get; set; }

    public virtual ICollection<TitulRequisitoModalidad> TitulRequisitoModalidad { get; set; } = new List<TitulRequisitoModalidad>();

    public virtual ICollection<TitulResponsableRequisitos> TitulResponsableRequisitos { get; set; } = new List<TitulResponsableRequisitos>();
}