// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class TitulPostulacionAlumnosRequisitosModalidad
{
    public int IdPostulacionAlumnoRequisitoModalidad { get; set; }

    public int IdPostulacionAlumnos { get; set; }

    public int IdRequisitoModalidad { get; set; }

    public int? IdAdjuntosImagenes { get; set; }

    public bool? ValorBool { get; set; }

    public virtual AdjuntosImagenes IdAdjuntosImagenesNavigation { get; set; }

    public virtual TitulPostulacionAlumnos IdPostulacionAlumnosNavigation { get; set; }

    public virtual TitulRequisitoModalidad IdRequisitoModalidadNavigation { get; set; }
}