// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class TitulPostulacionEstados
{
    public int IdPostulacionEstado { get; set; }

    public string Nombre { get; set; }

    public int Orden { get; set; }

    public bool EsFinal { get; set; }

    public bool EsActivo { get; set; }

    public virtual ICollection<TitulPostulacionAlumnos> TitulPostulacionAlumnos { get; set; } = new List<TitulPostulacionAlumnos>();
}