// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class TitulCohortes
{
    public int IdCohorte { get; set; }

    public string IdPeriodo { get; set; }

    public string Detelle { get; set; }

    public DateTime? FechaInicio { get; set; }

    public DateTime? FechaFin { get; set; }

    public int? DiasPermitidos { get; set; }

    public int? DiasExtension { get; set; }

    public bool? EsActivo { get; set; }

    public virtual Periodos IdPeriodoNavigation { get; set; }

    public virtual ICollection<TitulCohortesCarreras> TitulCohortesCarreras { get; set; } = new List<TitulCohortesCarreras>();
}