// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace TitulacionIstpet.Domain.Entities;

public partial class TitulResponsableEvidencia
{
    public int IdTitulResponsableEvidencia { get; set; }

    public int IdPostulacionAlumnoRequisitoModalidad { get; set; }

    public int IdResponsableEvidencias { get; set; }

    public string Estado { get; set; }

    public DateTime? Creado { get; set; }

    public DateTime? Actualizado { get; set; }

    public string IdCreado { get; set; }

    public string IdActualizado { get; set; }

    public string Observaciones { get; set; }

    public virtual TitulPostulacionAlumnosRequisitosModalidad IdPostulacionAlumnoRequisitoModalidadNavigation { get; set; }

    public virtual TitulResponsableRequisitos IdResponsableEvidenciasNavigation { get; set; }
}
