// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class TitulRequisitoModalidad
{
    public int IdRequisitoModalidad { get; set; }

    public int IdRequisitos { get; set; }

    public int IdModalidadTitulacion { get; set; }

    public bool? EsRequistoFinal { get; set; }

    public DateTime? FechaRegistro { get; set; }

    public DateTime? FechaDesactiva { get; set; }

    public bool EsActivo { get; set; }

    public virtual TitulModalidades IdModalidadTitulacionNavigation { get; set; }

    public virtual TitulRequisitos IdRequisitosNavigation { get; set; }

    public virtual ICollection<TitulPostulacionAlumnosRequisitosModalidad> TitulPostulacionAlumnosRequisitosModalidad { get; set; } = new List<TitulPostulacionAlumnosRequisitosModalidad>();
}