// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class TitulPostulacionAlumnos
{
    public int IdPostulacionAlumnos { get; set; }

    public int IdMatricula { get; set; }

    public int IdModalidadTitulacionCarrera { get; set; }

    public int IdPostulacionEstado { get; set; }

    public bool EsActivo { get; set; }

    public bool? EsCambioModalidad { get; set; }

    public virtual Matriculas IdMatriculaNavigation { get; set; }

    public virtual TitulModalidadesTitulacionCarreras IdModalidadTitulacionCarreraNavigation { get; set; }

    public virtual TitulPostulacionEstados IdPostulacionEstadoNavigation { get; set; }

    public virtual ICollection<TitulPostulacionAlumnosRequisitosModalidad> TitulPostulacionAlumnosRequisitosModalidad { get; set; } = new List<TitulPostulacionAlumnosRequisitosModalidad>();
}