// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class TitulResponsableRequisitos
{
    public int IdResponsableEvidencias { get; set; }

    public int IdRequisitos { get; set; }

    public string IdProfesor { get; set; }

    public virtual Profesores IdProfesorNavigation { get; set; }

    public virtual TitulRequisitos IdRequisitosNavigation { get; set; }

    public virtual ICollection<TitulResponsableEvidencia> TitulResponsableEvidencia { get; set; } = new List<TitulResponsableEvidencia>();
}
