// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class TitulCohortesCarreras
{
    public int IdCohorteCarrera { get; set; }

    public int IdModalidadCarrera { get; set; }

    public int IdCohorte { get; set; }

    public bool? EsActivo { get; set; }

    public virtual TitulCohortes IdCohorteNavigation { get; set; }

    public virtual ModalidadesCarreras IdModalidadCarreraNavigation { get; set; }

    public virtual ICollection<TitulModalidadesTitulacionCarreras> TitulModalidadesTitulacionCarreras { get; set; } = new List<TitulModalidadesTitulacionCarreras>();
}