// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class TitulModalidadesTitulacionCarreras
{
    public int IdModalidadTitulacionCarrera { get; set; }

    public int IdModalidadTitulacion { get; set; }

    public int IdCohorteCarrera { get; set; }

    public DateTime? FechaRegistro { get; set; }

    public bool? EsActivo { get; set; }

    public virtual TitulCohortesCarreras IdCohorteCarreraNavigation { get; set; }

    public virtual TitulModalidades IdModalidadTitulacionNavigation { get; set; }

    public virtual ICollection<TitulPostulacionAlumnos> TitulPostulacionAlumnos { get; set; } = new List<TitulPostulacionAlumnos>();
}