// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class TitulModalidades
{
    public int IdModalidadTitulacion { get; set; }

    public string ModalidadTitulacion { get; set; }

    public string EsComplexivo { get; set; }

    public string EsArticuloCientifico { get; set; }

    public string GeneraTesis { get; set; }

    public int? CantidadMinima { get; set; }

    public bool? EsActivo { get; set; }

    public virtual ICollection<TitulModalidadesTitulacionCarreras> TitulModalidadesTitulacionCarreras { get; set; } = new List<TitulModalidadesTitulacionCarreras>();

    public virtual ICollection<TitulRequisitoModalidad> TitulRequisitoModalidad { get; set; } = new List<TitulRequisitoModalidad>();
}