// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class TitulosProfesores
{
    public int IdTitulosProfesor { get; set; }

    public string IdProfesor { get; set; }

    public string Titulo { get; set; }

    public int IdUniversidad { get; set; }

    public int IdGradoAcademico { get; set; }

    public string CodigoSenescyt { get; set; }

    public DateOnly? FechaObtencion { get; set; }

    public DateOnly? FechaRegistro { get; set; }

    public int IdCampoDetalladoUnesco { get; set; }

    public string ArchivoTitulo { get; set; }

    public virtual CampoDetalladoUnesco IdCampoDetalladoUnescoNavigation { get; set; }

    public virtual GradosAcademicos IdGradoAcademicoNavigation { get; set; }

    public virtual Profesores IdProfesorNavigation { get; set; }

    public virtual Universidades IdUniversidadNavigation { get; set; }
}