// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Universidades
{
    public int IdUniversidad { get; set; }

    public int Idpaises { get; set; }

    public string Nombre { get; set; }

    public string CodigoSiees { get; set; }

    public virtual Paises IdpaisesNavigation { get; set; }

    public virtual ICollection<TitulosEnCurso> TitulosEnCurso { get; set; } = new List<TitulosEnCurso>();

    public virtual ICollection<TitulosProfesores> TitulosProfesores { get; set; } = new List<TitulosProfesores>();
}