// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Usuariosdepartamentossolicitudes
{
    public int IdUsuarioDepartamentoSolicitud { get; set; }

    public int? IdTipoSolicitud { get; set; }

    public int? IdUsuarioSolicitud { get; set; }

    public bool? Activo { get; set; }

    public DateTime? FechaRegistro { get; set; }

    public DateTime? FechaBaja { get; set; }

    public virtual Tipossolicitudes IdTipoSolicitudNavigation { get; set; }

    public virtual Usuariossolicitudes IdUsuarioSolicitudNavigation { get; set; }
}