// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Usuariossolicitudes
{
    public int IdUsuarioSolicitud { get; set; }

    public string Usuario { get; set; }

    public string Clave { get; set; }

    public bool? Resetear { get; set; }

    public string Email { get; set; }

    public bool? Activo { get; set; }

    public bool? Administrador { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<Usuariosdepartamentossolicitudes> Usuariosdepartamentossolicitudes { get; set; } = new List<Usuariosdepartamentossolicitudes>();
}