// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Usuarios
{
    public int IdUsuario { get; set; }

    /// <summary>
    /// este es idSifafi\n
    /// </summary>
    public string IdSigafi { get; set; }

    public string TablaSigafi { get; set; }

    public string Nombre { get; set; }

    public string Contrasenia { get; set; }

    public bool Activo { get; set; }

    public bool Administrador { get; set; }

    public string EmailInstitucional { get; set; }

    public bool EmailValidado { get; set; }

    public string HashEmailToken { get; set; }

    public DateTime? FechaEmailValidacion { get; set; }

    public virtual ICollection<BienApoyoFinanciero> BienApoyoFinanciero { get; set; } = new List<BienApoyoFinanciero>();

    public virtual ICollection<BienCaso> BienCaso { get; set; } = new List<BienCaso>();

    public virtual ICollection<BienCasoDesarrollo> BienCasoDesarrollo { get; set; } = new List<BienCasoDesarrollo>();

    public virtual ICollection<BienCasoRequerimiento> BienCasoRequerimiento { get; set; } = new List<BienCasoRequerimiento>();

    public virtual ICollection<BienPermisosSalidasAlumnos> BienPermisosSalidasAlumnos { get; set; } = new List<BienPermisosSalidasAlumnos>();

    public virtual ICollection<BienPostulacionRequisitosBecas> BienPostulacionRequisitosBecas { get; set; } = new List<BienPostulacionRequisitosBecas>();

    public virtual ICollection<BienPostulacionesBecas> BienPostulacionesBecas { get; set; } = new List<BienPostulacionesBecas>();

    public virtual ICollection<BienResolucionesTribunales> BienResolucionesTribunales { get; set; } = new List<BienResolucionesTribunales>();

    public virtual BienTribunal BienTribunal { get; set; }

    public virtual ICollection<BienUsuarioCaso> BienUsuarioCaso { get; set; } = new List<BienUsuarioCaso>();

    public virtual ICollection<GestPasswordResets> GestPasswordResets { get; set; } = new List<GestPasswordResets>();

    public virtual ICollection<KardexVacaciones> KardexVacaciones { get; set; } = new List<KardexVacaciones>();

    public virtual ICollection<RbacRefreshTokens> RbacRefreshTokens { get; set; } = new List<RbacRefreshTokens>();

    public virtual ICollection<RbacUsuarioRol> RbacUsuarioRol { get; set; } = new List<RbacUsuarioRol>();

    public virtual ICollection<SolicitudesLicencias> SolicitudesLicencias { get; set; } = new List<SolicitudesLicencias>();
}