// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class VacCierresColectivosExclusiones
{
    public int IdExclusion { get; set; }

    public int IdCierre { get; set; }

    public string IdProfesor { get; set; }

    public virtual VacCierresColectivos IdCierreNavigation { get; set; }
}