// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class VacConfigDiasExtrasExcepciones
{
    public int IdExcepcion { get; set; }

    public int IdConfig { get; set; }

    public string IdProfesor { get; set; }

    public string Tipo { get; set; }

    public virtual VacConfigDiasExtrasDepto IdConfigNavigation { get; set; }

    public virtual Profesores IdProfesorNavigation { get; set; }
}