// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class VacCierresColectivos
{
    public int IdCierre { get; set; }

    public string Nombre { get; set; }

    public DateOnly FechaInicio { get; set; }

    public DateOnly FechaFin { get; set; }

    public decimal DiasDescuento { get; set; }

    public int FinesSemanaIncluidos { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int RegistradoPorId { get; set; }

    public virtual ICollection<VacCierresColectivosExclusiones> VacCierresColectivosExclusiones { get; set; } = new List<VacCierresColectivosExclusiones>();
}