// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class VacLedger
{
    public int IdLedger { get; set; }

    public string IdProfesor { get; set; }

    public string TipoTransaccion { get; set; }

    public decimal Dias { get; set; }

    public int FinesSemana { get; set; }

    public DateTime Fecha { get; set; }

    public string Periodo { get; set; }

    public string Detalle { get; set; }

    public int? IdPeriodoVacaciones { get; set; }

    public int? IdPermiso { get; set; }

    public int? RegistradoPorId { get; set; }
}