// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class VacPlantillasDocumentos
{
    public int IdPlantilla { get; set; }

    public string Codigo { get; set; }

    public string Nombre { get; set; }

    public string Cuerpo { get; set; }

    public bool? Activo { get; set; }

    public DateTime FechaActualizacion { get; set; }
}