// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class VacRecuperacionFeriados
{
    public int IdRecuperacionFeriado { get; set; }

    public int IdDiasEspeciales { get; set; }

    public string IdProfesor { get; set; }

    public DateOnly FechaRecuperacion { get; set; }

    public bool Completado { get; set; }

    public string Observacion { get; set; }

    public int? RegistradoPorId { get; set; }
}