// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class VacRecuperacionTiempo
{
    public int IdRecuperacion { get; set; }

    public int IdPermiso { get; set; }

    public DateOnly FechaRecuperada { get; set; }

    public decimal HorasRecuperadas { get; set; }

    public DateTime FechaRegistro { get; set; }

    public int UsuarioTh { get; set; }

    public virtual VacPermisos IdPermisoNavigation { get; set; }
}