// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class VacSaldos
{
    public int IdSaldoVacaciones { get; set; }

    public string IdProfesor { get; set; }

    public string Periodo { get; set; }

    public decimal DiasGanados { get; set; }

    public decimal DiasTomados { get; set; }

    public decimal DiasAcumulados { get; set; }

    public int FinesSemanaTomados { get; set; }

    public DateOnly FechaUltimoCalculo { get; set; }

    public bool? Activo { get; set; }
}