// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Vinculacionproyectosplanesaprendizaje
{
    public int IdProyectosPlanesAprendizaje { get; set; }

    public int? IdProyectoVinculacion { get; set; }

    public int? IdProyectosResultadosAprendizaje { get; set; }

    public string Actividad { get; set; }

    public DateTime? FechaRegistro { get; set; }

    public bool Activo { get; set; }

    public virtual Vinculacionproyectos IdProyectoVinculacionNavigation { get; set; }

    public virtual Vinculacionproyectosresultadosaprendizaje IdProyectosResultadosAprendizajeNavigation { get; set; }
}