// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Vinculacionproyectoscarrerasdetalle
{
    public int IdProyectoCarrera { get; set; }

    public int? IdProyectoVinculacion { get; set; }

    public int? IdTipoPoblacion { get; set; }

    public string Poblacion { get; set; }

    public string Descripcion { get; set; }

    public int? Orden { get; set; }

    public virtual Vinculacionproyectos IdProyectoVinculacionNavigation { get; set; }

    public virtual Vinculaciontipospoblaciones IdTipoPoblacionNavigation { get; set; }
}