// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Vinculacionlineasaccion
{
    public int IdlineaAsccion { get; set; }

    public string Linea { get; set; }

    public bool? Activo { get; set; }

    public virtual ICollection<Vinculacionproyectos> Vinculacionproyectos { get; set; } = new List<Vinculacionproyectos>();
}