// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Vinculacionproyectosobjetivos
{
    public int IdProyectoObjetivo { get; set; }

    public int? IdProyectoVinculacion { get; set; }

    public string Objetivo { get; set; }

    public bool? EsGeneral { get; set; }

    public string Resultado { get; set; }

    public int? Orden { get; set; }

    public bool? Activo { get; set; }

    public virtual Vinculacionproyectos IdProyectoVinculacionNavigation { get; set; }

    public virtual ICollection<Vinculacionproyectosplantrabajo> Vinculacionproyectosplantrabajo { get; set; } = new List<Vinculacionproyectosplantrabajo>();
}