// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Vinculacionproyectoshabilidadesblandas
{
    public int IdProyectoHabilidad { get; set; }

    public int? IdProyectoVinculacion { get; set; }

    public int? IdHablidadBlanda { get; set; }

    public int? Orden { get; set; }

    public bool? Activo { get; set; }

    public virtual Vinculacionhabilidadesblandas IdHablidadBlandaNavigation { get; set; }

    public virtual Vinculacionproyectos IdProyectoVinculacionNavigation { get; set; }
}