// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Vinculacioncategoriasobjetivosoportunidades
{
    public int IdCategoriaObjetivoOportunidad { get; set; }

    public string CategoriaObjetivoOportunidad { get; set; }

    public bool? Activo { get; set; }

    public virtual ICollection<Vinculacionobjetivosoportunidades> Vinculacionobjetivosoportunidades { get; set; } = new List<Vinculacionobjetivosoportunidades>();
}