// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Vinculacionobjetivosoportunidades
{
    public int IdObjetivoOportunidad { get; set; }

    public int? IdCategoriaObjetivoOportunidad { get; set; }

    public string ObjetivoOportunidad { get; set; }

    public bool? Activo { get; set; }

    public virtual Vinculacioncategoriasobjetivosoportunidades IdCategoriaObjetivoOportunidadNavigation { get; set; }

    public virtual ICollection<Vinculacionproyectosobjetivosoportunidades> Vinculacionproyectosobjetivosoportunidades { get; set; } = new List<Vinculacionproyectosobjetivosoportunidades>();
}