// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Vinculacionproyectosimpactos
{
    public int IdProyectoImpacto { get; set; }

    public int? IdProyectoVinculacion { get; set; }

    public int? IdImpactoproyecto { get; set; }

    public bool? Activo { get; set; }

    public virtual Vinculacionimpactosproyectos IdImpactoproyectoNavigation { get; set; }

    public virtual Vinculacionproyectos IdProyectoVinculacionNavigation { get; set; }

    public virtual ICollection<Vinculacionproyectosplantrabajo> Vinculacionproyectosplantrabajo { get; set; } = new List<Vinculacionproyectosplantrabajo>();
}