// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Vinculacionhabilidadesblandas
{
    public int IdHablidadBlanda { get; set; }

    public string HabilidadBlanda { get; set; }

    public string Descripcion { get; set; }

    public bool? Activo { get; set; }

    public virtual ICollection<Vinculacionproyectoshabilidadesblandas> Vinculacionproyectoshabilidadesblandas { get; set; } = new List<Vinculacionproyectoshabilidadesblandas>();
}