// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Vinculacionproyectoscarreras
{
    public int IdProyectoCarrera { get; set; }

    public int? IdProyectoVinculacion { get; set; }

    public int? IdCarrera { get; set; }

    public bool? EsPrincipal { get; set; }

    public bool? Activo { get; set; }

    public virtual Carreras IdCarreraNavigation { get; set; }

    public virtual Vinculacionproyectos IdProyectoVinculacionNavigation { get; set; }
}