// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Vinculacionobjetivospedis
{
    public int IdObjetivoPedi { get; set; }

    public string Pedi { get; set; }

    public string ObjetivoPedi { get; set; }

    public bool? Activo { get; set; }

    public virtual ICollection<Vinculacionproyectosobjetivospedis> Vinculacionproyectosobjetivospedis { get; set; } = new List<Vinculacionproyectosobjetivospedis>();
}