// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Vinculacionpoblacionindirecta
{
    public int IdPoblacionIndirecta { get; set; }

    public string Indirecta { get; set; }

    public bool Activo { get; set; }
}