// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Vinculacioncategoriasresultadosaprendizajes
{
    public int IdCategoriaResultadoAprendizaje { get; set; }

    public string CategoriaResultadoAprendizaje { get; set; }

    public bool? Activo { get; set; }

    public virtual ICollection<Vinculacionproyectosresultadosaprendizaje> Vinculacionproyectosresultadosaprendizaje { get; set; } = new List<Vinculacionproyectosresultadosaprendizaje>();
}