// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Vinculacionproyectosobjetivospedis
{
    public int IdProyectoObjetivoPedi { get; set; }

    public int? IdProyectoVinculacion { get; set; }

    public int? IdObjetivoPedi { get; set; }

    public int? Orden { get; set; }

    public bool? Activo { get; set; }

    public virtual Vinculacionobjetivospedis IdObjetivoPediNavigation { get; set; }

    public virtual Vinculacionproyectos IdProyectoVinculacionNavigation { get; set; }
}