// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Vinculacionproyectosperiodos
{
    public int IdProyectoPeriodo { get; set; }

    public int? IdProyectoVinculacion { get; set; }

    public string IdPeriodo { get; set; }

    public bool? EsPrincipal { get; set; }

    public bool? Activo { get; set; }

    public virtual Vinculacionproyectos IdProyectoVinculacionNavigation { get; set; }
}