// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Vinculacionproyectos
{
    public int IdProyectoVinculacion { get; set; }

    public int? IdProgramaVinculacion { get; set; }

    public string Proyecto { get; set; }

    public int? IdCampoDetalladoUnesco { get; set; }

    public int? IdlineaAsccion { get; set; }

    public bool? EsAsistenciaComunitaria { get; set; }

    public bool? EsEducacionContinua { get; set; }

    public string TiempoEstimado { get; set; }

    public string ResumenEjecutivo { get; set; }

    public string Antecedentes { get; set; }

    public string AlcanceTerritorial { get; set; }

    public string Metodologia { get; set; }

    public string Impacto { get; set; }

    public string Innovacion { get; set; }

    public string HabilidadesDescripcion { get; set; }

    public string IdProfesor { get; set; }

    public bool? Activo { get; set; }

    public int? IdPoblacionDirecta { get; set; }

    public int? IdPoblacionIndirecta { get; set; }

    public int? IdPoblacionExterna { get; set; }

    public string Biografia { get; set; }

    public virtual CampoDetalladoUnesco IdCampoDetalladoUnescoNavigation { get; set; }

    public virtual Vinculacionlineasaccion IdlineaAsccionNavigation { get; set; }

    public virtual ICollection<Vinculacionproyectosalumnos> Vinculacionproyectosalumnos { get; set; } = new List<Vinculacionproyectosalumnos>();

    public virtual ICollection<Vinculacionproyectoscarreras> Vinculacionproyectoscarreras { get; set; } = new List<Vinculacionproyectoscarreras>();

    public virtual ICollection<Vinculacionproyectoscarrerasdetalle> Vinculacionproyectoscarrerasdetalle { get; set; } = new List<Vinculacionproyectoscarrerasdetalle>();

    public virtual ICollection<Vinculacionproyectoscronograma> Vinculacionproyectoscronograma { get; set; } = new List<Vinculacionproyectoscronograma>();

    public virtual ICollection<Vinculacionproyectosentidades> Vinculacionproyectosentidades { get; set; } = new List<Vinculacionproyectosentidades>();

    public virtual ICollection<Vinculacionproyectoshabilidadesblandas> Vinculacionproyectoshabilidadesblandas { get; set; } = new List<Vinculacionproyectoshabilidadesblandas>();

    public virtual ICollection<Vinculacionproyectosimpactos> Vinculacionproyectosimpactos { get; set; } = new List<Vinculacionproyectosimpactos>();

    public virtual ICollection<Vinculacionproyectosmateriales> Vinculacionproyectosmateriales { get; set; } = new List<Vinculacionproyectosmateriales>();

    public virtual ICollection<Vinculacionproyectosobjetivos> Vinculacionproyectosobjetivos { get; set; } = new List<Vinculacionproyectosobjetivos>();

    public virtual ICollection<Vinculacionproyectosobjetivosoportunidades> Vinculacionproyectosobjetivosoportunidades { get; set; } = new List<Vinculacionproyectosobjetivosoportunidades>();

    public virtual ICollection<Vinculacionproyectosobjetivospedis> Vinculacionproyectosobjetivospedis { get; set; } = new List<Vinculacionproyectosobjetivospedis>();

    public virtual ICollection<Vinculacionproyectosperiodos> Vinculacionproyectosperiodos { get; set; } = new List<Vinculacionproyectosperiodos>();

    public virtual ICollection<Vinculacionproyectosplanesaprendizaje> Vinculacionproyectosplanesaprendizaje { get; set; } = new List<Vinculacionproyectosplanesaprendizaje>();

    public virtual ICollection<Vinculacionproyectosplantrabajo> Vinculacionproyectosplantrabajo { get; set; } = new List<Vinculacionproyectosplantrabajo>();

    public virtual ICollection<Vinculacionproyectospoblaciones> Vinculacionproyectospoblaciones { get; set; } = new List<Vinculacionproyectospoblaciones>();

    public virtual ICollection<Vinculacionproyectospresupuestos> Vinculacionproyectospresupuestos { get; set; } = new List<Vinculacionproyectospresupuestos>();

    public virtual ICollection<Vinculacionproyectosprofesores> Vinculacionproyectosprofesores { get; set; } = new List<Vinculacionproyectosprofesores>();

    public virtual ICollection<Vinculacionproyectosresponsables> Vinculacionproyectosresponsables { get; set; } = new List<Vinculacionproyectosresponsables>();

    public virtual ICollection<Vinculacionproyectosresultadosaprendizaje> Vinculacionproyectosresultadosaprendizaje { get; set; } = new List<Vinculacionproyectosresultadosaprendizaje>();
}