// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Vinculacionproyectosprofesores
{
    public int IdProyectoProfesor { get; set; }

    public int? IdProyectoVinculacion { get; set; }

    public string IdProfesor { get; set; }

    public bool? EsDirector { get; set; }

    public bool? Activo { get; set; }

    public virtual Vinculacionproyectos IdProyectoVinculacionNavigation { get; set; }
}