// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Vinculacionproyectosalumnos
{
    public int IdProyectoAlumno { get; set; }

    public int? IdProyectoVinculacion { get; set; }

    public int? IdMatricula { get; set; }

    public bool? Activo { get; set; }

    public virtual Matriculas IdMatriculaNavigation { get; set; }

    public virtual Vinculacionproyectos IdProyectoVinculacionNavigation { get; set; }
}