// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Vinculacionproyectosentidades
{
    public int IdProyectoEntidad { get; set; }

    public int? IdProyectoVinculacion { get; set; }

    public string Entidad { get; set; }

    public string TipoEntidad { get; set; }

    public bool? Activo { get; set; }

    public virtual Vinculacionproyectos IdProyectoVinculacionNavigation { get; set; }
}