// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Vinculaciontiposobjetivos
{
    public int IdTipoObjetivo { get; set; }

    public string TipoObjetivo { get; set; }

    public bool? EsGeneral { get; set; }

    public bool? Activo { get; set; }
}