// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Vinculacionproyectosresultadosaprendizaje
{
    public int IdProyectosResultadosAprendizaje { get; set; }

    public int? IdProyectoVinculacion { get; set; }

    public int? IdCategoriaResultadoAprendizaje { get; set; }

    public string Resultado { get; set; }

    public DateTime? FechaRegistro { get; set; }

    public bool Activo { get; set; }

    public virtual Vinculacioncategoriasresultadosaprendizajes IdCategoriaResultadoAprendizajeNavigation { get; set; }

    public virtual Vinculacionproyectos IdProyectoVinculacionNavigation { get; set; }

    public virtual ICollection<Vinculacionproyectosplanesaprendizaje> Vinculacionproyectosplanesaprendizaje { get; set; } = new List<Vinculacionproyectosplanesaprendizaje>();
}