// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TitulacionIstpet.Domain.Entities;

public partial class Vinculacionestadosproyectos
{
    public int IdEstadoProyecto { get; set; }

    public string Estado { get; set; }

    public int? Orden { get; set; }

    public bool? Activo { get; set; }
}