// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class adjuntos_imagenes
{
    public int idAdjuntos_Imagenes { get; set; }

    public string NombreArchivos { get; set; }

    public string Extension { get; set; }

    public string MimeTypes { get; set; }

    public int? TamanioBytes { get; set; }

    public string Ruta { get; set; }

    public virtual ICollection<bien_caso_desarrollo_doc> bien_caso_desarrollo_doc { get; set; } = new List<bien_caso_desarrollo_doc>();

    public virtual ICollection<bien_caso_requerimiento> bien_caso_requerimiento { get; set; } = new List<bien_caso_requerimiento>();

    public virtual ICollection<bien_motivo_apertura> bien_motivo_apertura { get; set; } = new List<bien_motivo_apertura>();

    public virtual ICollection<bien_postulacion_requisitos_becas> bien_postulacion_requisitos_becas { get; set; } = new List<bien_postulacion_requisitos_becas>();

    public virtual ICollection<carreras_adjuntos> carreras_adjuntos { get; set; } = new List<carreras_adjuntos>();

    public virtual ICollection<plantilla_contrato> plantilla_contratoidFondoNavigation { get; set; } = new List<plantilla_contrato>();

    public virtual ICollection<plantilla_contrato> plantilla_contratoidSelloNavigation { get; set; } = new List<plantilla_contrato>();
}