// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class administrador
{
    public string idAdministrador { get; set; }

    public string NombresCompletos { get; set; }

    public string ApellidosCompletos { get; set; }

    public string password { get; set; }

    public sbyte? esAdministrador { get; set; }

    public DateOnly? fecha_Asignacion { get; set; }

    public DateOnly? fecha_modificacion { get; set; }

    public sbyte? esActivo { get; set; }

    public sbyte? primerIngreso { get; set; }
}