// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class agenda_academica
{
    public string idperiodo { get; set; }

    public DateOnly? fecha_desde { get; set; }

    public DateOnly? fecha_hasta { get; set; }

    public string evento { get; set; }
}