// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class alumnos_acta_conduccion
{
    public string idalumno { get; set; }

    public int? numero_acta { get; set; }

    public DateOnly? fecha_grado { get; set; }

    public string idperiodo { get; set; }
}