// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class alumnos_referencias
{
    public int idalumnos_referencias { get; set; }

    public string idAlumno { get; set; }

    public string nombres_referencia { get; set; }

    public string contacto { get; set; }

    public string referencia_empresa { get; set; }

    public string relacion { get; set; }

    public DateOnly? fecha_creacion { get; set; }

    public DateOnly? fecha_modificacion { get; set; }
}