// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class alumnos_sucesos
{
    public int idSuceso { get; set; }

    public string idAlumno { get; set; }

    public int? idMatricula { get; set; }

    public DateTime fechaRegistro { get; set; }

    public string observacion { get; set; }

    public string usuario { get; set; }
}