// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class alumnos_restricciones
{
    public string idalumno { get; set; }

    public string idrestriccion { get; set; }
}