// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class alumnos_inscripciones_ingles
{
    public string idAlumno { get; set; }

    public string idPeriodo { get; set; }

    public DateTime fechaRegistro { get; set; }

    public string user_inscripcion { get; set; }

    public decimal? puntaje { get; set; }

    public int? idAsignatura { get; set; }

    public int? idMalla { get; set; }

    public string observacion { get; set; }
}