// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class asignaciones_profesores_grado
{
    public string idProfesor { get; set; }

    public int idAsignatura { get; set; }

    public string idPeriodo { get; set; }

    public int idModalidad { get; set; }

    public int idSeccion { get; set; }

    public int idNivel { get; set; }

    public string paralelo { get; set; }

    public sbyte? activo { get; set; }
}