// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class asignacion_instructores_vehiculos
{
    public int idAsignacion { get; set; }

    public int idVehiculo { get; set; }

    public string idProfesor { get; set; }

    public DateOnly? fecha_asignacion { get; set; }

    public DateOnly? fecha_salidad { get; set; }

    public bool? activo { get; set; }

    public string usuario_asigna { get; set; }

    public string usuario_desactiva { get; set; }

    public string observacion { get; set; }
}