// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class asignaturas_complementos_formacion
{
    public int idAsignatura { get; set; }

    public int? idCarrera { get; set; }

    public string asignatura { get; set; }

    public sbyte? activo { get; set; }
}