// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class audit_logs
{
    public int id { get; set; }

    public string usuario { get; set; }

    public string accion { get; set; }

    public string entidad_id { get; set; }

    public string detalles { get; set; }

    public string ip_origen { get; set; }

    public DateTime fecha_hora { get; set; }
}