// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class bien_caso_desarrollo
{
    public int idCasoDesarrollo { get; set; }

    public int idCaso { get; set; }

    public int? idCasoDesarrolloPadre { get; set; }

    public int idTipoDesarrollo { get; set; }

    public string titulo { get; set; }

    public string descripcion { get; set; }

    public string observaciones { get; set; }

    public int orden { get; set; }

    public string estado { get; set; }

    public DateTime fechaPlanificada { get; set; }

    public DateTime? fechaReal { get; set; }

    public int? idUsuarioResponsable { get; set; }

    public int? casoAbierto { get; set; }

    public virtual ICollection<bien_caso_desarrollo> InverseidCasoDesarrolloPadreNavigation { get; set; } = new List<bien_caso_desarrollo>();

    public virtual ICollection<bien_asistentes_desarrollo> bien_asistentes_desarrollo { get; set; } = new List<bien_asistentes_desarrollo>();

    public virtual ICollection<bien_caso_desarrollo_doc> bien_caso_desarrollo_doc { get; set; } = new List<bien_caso_desarrollo_doc>();

    public virtual bien_caso_desarrollo idCasoDesarrolloPadreNavigation { get; set; }

    public virtual bien_caso idCasoNavigation { get; set; }

    public virtual bien_tipo_desarrollo idTipoDesarrolloNavigation { get; set; }

    public virtual usuarios idUsuarioResponsableNavigation { get; set; }
}