// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class bien_apoyo_financiero
{
    public int idApoyoFinanciero { get; set; }

    public int idResponsable { get; set; }

    public int idResolucionesTribunales { get; set; }

    public int idMatricula { get; set; }

    public string observacion { get; set; }

    public sbyte esAceptada { get; set; }

    public DateOnly? fechaAceptacion { get; set; }

    public sbyte esActivo { get; set; }

    public virtual matriculas idMatriculaNavigation { get; set; }

    public virtual bien_resoluciones_tribunales idResolucionesTribunalesNavigation { get; set; }

    public virtual usuarios idResponsableNavigation { get; set; }
}