// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class bien_tipo_convocatoria
{
    public int idTipoConvocatoria { get; set; }

    public string detalle { get; set; }

    public sbyte esActivo { get; set; }

    public sbyte esInformativo { get; set; }

    public sbyte bloquea { get; set; }

    public virtual ICollection<bien_convocatorias_becas> bien_convocatorias_becas { get; set; } = new List<bien_convocatorias_becas>();
}