// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class bien_postulacion_requisitos_becas
{
    public int idPostulacionBecaDocumentos { get; set; }

    public int idParametroRequisitoBeca { get; set; }

    public string estadoDocumento { get; set; }

    public string observacionBienestar { get; set; }

    public DateTime? fechaValidacionBienestar { get; set; }

    public DateTime fechaRegistro { get; set; }

    public sbyte esActivo { get; set; }

    public int idPostulacionesBecas { get; set; }

    public int? idUsuarioBienestar { get; set; }

    public sbyte? requisitoBool { get; set; }

    public int? requisitoAdjunto { get; set; }

    public virtual bien_parametro_requisito_beca idParametroRequisitoBecaNavigation { get; set; }

    public virtual bien_postulaciones_becas idPostulacionesBecasNavigation { get; set; }

    public virtual usuarios idUsuarioBienestarNavigation { get; set; }

    public virtual adjuntos_imagenes requisitoAdjuntoNavigation { get; set; }
}