// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class bien_datos_educacion
{
    public int idDatosEducacion { get; set; }

    public string nombreCurso { get; set; }

    public string nombreInstitucion { get; set; }

    public sbyte esIstpet { get; set; }

    public string nivelEducacion { get; set; }

    public sbyte estaCursando { get; set; }

    public sbyte esPresencial { get; set; }

    public sbyte esBecado { get; set; }

    public string tipoEducacion { get; set; }

    public string idAlumno { get; set; }

    public virtual alumnos idAlumnoNavigation { get; set; }
}