// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class bien_tipo_sujeto
{
    public int idTipoSujeto { get; set; }

    public string detalle { get; set; }

    public sbyte esActivo { get; set; }

    public virtual ICollection<bien_usuario_caso> bien_usuario_caso { get; set; } = new List<bien_usuario_caso>();
}