// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class bien_datos_economicos
{
    public int idFichaSocioEconomica { get; set; }

    public sbyte familiaRecibeBono { get; set; }

    public string tipoActividadEconomica { get; set; }

    public decimal ingresosPropios { get; set; }

    public string empleaIngresos { get; set; }

    public string nombreBono { get; set; }

    public virtual bien_ficha_socioeconomica idFichaSocioEconomicaNavigation { get; set; }
}