// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class bien_servicios_fichas
{
    public int idServicioFicha { get; set; }

    public sbyte tieneServicio { get; set; }

    public int idTipoServicio { get; set; }

    public int idFichaSocioEconomica { get; set; }

    public virtual bien_ficha_socioeconomica idFichaSocioEconomicaNavigation { get; set; }

    public virtual bien_tipo_servicios idTipoServicioNavigation { get; set; }
}