// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class bien_caso_requerimiento
{
    public int idCasoRequerimiento { get; set; }

    public int idCaso { get; set; }

    public int idRequerimientoMotivoApertura { get; set; }

    /// <summary>
    /// snapshot del catalogo al abrir
    /// </summary>
    public string detalle { get; set; }

    /// <summary>
    /// snapshot del catalogo al abrir
    /// </summary>
    public sbyte esObligatorio { get; set; }

    public sbyte cumplido { get; set; }

    public int? idAdjuntos_Imagenes { get; set; }

    public int? idUsuarioCumplio { get; set; }

    public DateTime? fechaCumplimiento { get; set; }

    public string observacion { get; set; }

    public virtual adjuntos_imagenes idAdjuntos_ImagenesNavigation { get; set; }

    public virtual bien_caso idCasoNavigation { get; set; }

    public virtual bien_requerimientos_motivo_apertura idRequerimientoMotivoAperturaNavigation { get; set; }

    public virtual usuarios idUsuarioCumplioNavigation { get; set; }
}