// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class bien_motivo_apertura
{
    public int idMotivoApertura { get; set; }

    public string nombre { get; set; }

    public string descripcionMotivoApertura { get; set; }

    public string accionesPrevias { get; set; }

    /// <summary>
    /// plantilla/formato opcional asociado al motivo
    /// </summary>
    public int? idAdjuntos_Imagenes { get; set; }

    public sbyte esActivo { get; set; }

    public virtual ICollection<bien_caso> bien_caso { get; set; } = new List<bien_caso>();

    public virtual ICollection<bien_requerimientos_motivo_apertura> bien_requerimientos_motivo_apertura { get; set; } = new List<bien_requerimientos_motivo_apertura>();

    public virtual adjuntos_imagenes idAdjuntos_ImagenesNavigation { get; set; }
}