// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class bien_parentezcos_alumno
{
    public int idParentezcoAlumno { get; set; }

    public int idParentezco { get; set; }

    public string idAlumno { get; set; }

    public int? idpaises { get; set; }

    public int? idNivelInstruccion { get; set; }

    public string nombre { get; set; }

    public decimal? ingresoMensualPromedio { get; set; }

    public sbyte esResponsableEconomico { get; set; }

    public sbyte contactoEmergencia { get; set; }

    public string numeroContactoEmergencia { get; set; }

    public sbyte? esCarga { get; set; }

    public sbyte? tieneDiscapacidad { get; set; }

    public sbyte esActivo { get; set; }

    public virtual alumnos idAlumnoNavigation { get; set; }

    public virtual bien_nivel_instruccion idNivelInstruccionNavigation { get; set; }

    public virtual bien_parentescos idParentezcoNavigation { get; set; }

    public virtual paises idpaisesNavigation { get; set; }
}