// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class bien_tipo_cargo_tribunal
{
    public int idTipoCargoTribunal { get; set; }

    public string detalle { get; set; }

    public sbyte? esRector { get; set; }

    public virtual ICollection<bien_tribunal> bien_tribunal { get; set; } = new List<bien_tribunal>();

    public virtual ICollection<bien_votos_tribunales> bien_votos_tribunales { get; set; } = new List<bien_votos_tribunales>();
}