// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class bien_ficha_acompañamiento
{
    public int idFichaAcompañamiento { get; set; }

    public int idActaReunion { get; set; }

    public string recomedacionesDocenteEspecial { get; set; }

    public string situacionIdentificada { get; set; }

    public string codigoCaso { get; set; }

    public DateTime? fechaEmision { get; set; }

    public string bien_ficha_acompañamientocol { get; set; }
}