// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class bien_tipo_desarrollo
{
    public int idTipoDesarrollo { get; set; }

    public string detalle { get; set; }

    public sbyte esCierre { get; set; }

    public sbyte esActivo { get; set; }

    public virtual ICollection<bien_caso_desarrollo> bien_caso_desarrollo { get; set; } = new List<bien_caso_desarrollo>();
}