// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class bien_tipo_servicios
{
    public int idTipoServicio { get; set; }

    public string nombre { get; set; }

    public sbyte esActivo { get; set; }

    public virtual ICollection<bien_servicios_fichas> bien_servicios_fichas { get; set; } = new List<bien_servicios_fichas>();
}