// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class bien_asistentes_desarrollo
{
    public int idbien_asistentes_desarrollo { get; set; }

    public int idCasoDesarrollo { get; set; }

    public int idUsuarioCaso { get; set; }

    /// <summary>
    /// NULL = aun no registrado
    /// </summary>
    public sbyte? asistio { get; set; }

    public string observacion { get; set; }

    public virtual bien_caso_desarrollo idCasoDesarrolloNavigation { get; set; }

    public virtual bien_usuario_caso idUsuarioCasoNavigation { get; set; }
}