// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class bien_requisitos_beca
{
    public int idRequistosBeca { get; set; }

    public string requisito { get; set; }

    public string tipoRequisito { get; set; }

    public sbyte esActivo { get; set; }

    public virtual ICollection<bien_parametro_requisito_beca> bien_parametro_requisito_beca { get; set; } = new List<bien_parametro_requisito_beca>();
}