// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class bien_genero_alumno
{
    public int idGeneroAlumno { get; set; }

    public string detalle { get; set; }

    public virtual ICollection<alumnos> alumnos { get; set; } = new List<alumnos>();
}