// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class bien_convocatorias_becas
{
    public int idConvocatoriasBecas { get; set; }

    public DateOnly fechaInicio { get; set; }

    public DateOnly? fechaFin { get; set; }

    public int? idDetalleCronograma { get; set; }

    public int idTipoConvocatoria { get; set; }

    public virtual ICollection<bien_postulaciones_becas> bien_postulaciones_becas { get; set; } = new List<bien_postulaciones_becas>();

    public virtual cron_detalle_cronograma idDetalleCronogramaNavigation { get; set; }

    public virtual bien_tipo_convocatoria idTipoConvocatoriaNavigation { get; set; }
}