// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class bien_motivos_beca
{
    public int idMotivosBeca { get; set; }

    public sbyte esActivo { get; set; }

    public string motivoBeca { get; set; }

    public sbyte? esDefault { get; set; }

    public int idTipoApoyoFinanciero { get; set; }

    public int idPorcentajeBeca { get; set; }

    public virtual ICollection<bien_postulaciones_becas> bien_postulaciones_becas { get; set; } = new List<bien_postulaciones_becas>();

    public virtual bien_porcentaje_beca idPorcentajeBecaNavigation { get; set; }

    public virtual bien_tipo_apoyo_financiero idTipoApoyoFinancieroNavigation { get; set; }
}