// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class bien_caso
{
    public int idCaso { get; set; }

    public string codigoCaso { get; set; }

    public int idMotivoApertura { get; set; }

    public string idPeriodo { get; set; }

    public int idUsuarioResponsableCaso { get; set; }

    public string accionesRealizadas { get; set; }

    public string conclusionesCierre { get; set; }

    public DateTime fechaCreacion { get; set; }

    public DateTime? fechaActualizacion { get; set; }

    public string estado { get; set; }

    public virtual ICollection<bien_caso_desarrollo> bien_caso_desarrollo { get; set; } = new List<bien_caso_desarrollo>();

    public virtual ICollection<bien_caso_requerimiento> bien_caso_requerimiento { get; set; } = new List<bien_caso_requerimiento>();

    public virtual ICollection<bien_usuario_caso> bien_usuario_caso { get; set; } = new List<bien_usuario_caso>();

    public virtual bien_motivo_apertura idMotivoAperturaNavigation { get; set; }

    public virtual periodos idPeriodoNavigation { get; set; }

    public virtual usuarios idUsuarioResponsableCasoNavigation { get; set; }
}