// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class bien_caso_desarrollo_doc
{
    public int idCasoDesarrolloDoc { get; set; }

    public int idCasoDesarrollo { get; set; }

    public int idAdjuntos_Imagenes { get; set; }

    public virtual adjuntos_imagenes idAdjuntos_ImagenesNavigation { get; set; }

    public virtual bien_caso_desarrollo idCasoDesarrolloNavigation { get; set; }
}