// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class bien_detalle_vivienda
{
    public string idAlumno { get; set; }

    public string tipoDeVivienda { get; set; }

    public int espaciosFisicos { get; set; }

    public int dormitorios { get; set; }

    public string referencia { get; set; }

    public int? miembrosHogar { get; set; }

    public int? adultosVivienda { get; set; }

    public int? niñosVivienda { get; set; }

    public sbyte? bonoDesarrolloHumano { get; set; }

    public decimal? ingresoPromedioHogar { get; set; }

    public int idFichaSocioEconomica { get; set; }

    public virtual bien_ficha_socioeconomica idFichaSocioEconomicaNavigation { get; set; }
}