// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class bien_tipo_vivienda
{
    public int idTipoVivienda { get; set; }

    public string detalle { get; set; }

    public virtual ICollection<bien_ficha_socioeconomica> bien_ficha_socioeconomica { get; set; } = new List<bien_ficha_socioeconomica>();
}