// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class bien_requerimientos_motivo_apertura
{
    public int idRequerimientoMotivoApertura { get; set; }

    public string detalle { get; set; }

    public int idMotivoApertura { get; set; }

    public sbyte esObligatorio { get; set; }

    public sbyte esActivo { get; set; }

    public virtual ICollection<bien_caso_requerimiento> bien_caso_requerimiento { get; set; } = new List<bien_caso_requerimiento>();

    public virtual bien_motivo_apertura idMotivoAperturaNavigation { get; set; }
}