// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class bien_usuario_caso
{
    public int idUsuarioCaso { get; set; }

    public int idTipoSujeto { get; set; }

    public int idUsuario { get; set; }

    public int idCaso { get; set; }

    public string rol { get; set; }

    public string detalle { get; set; }

    public virtual ICollection<bien_asistentes_desarrollo> bien_asistentes_desarrollo { get; set; } = new List<bien_asistentes_desarrollo>();

    public virtual bien_caso idCasoNavigation { get; set; }

    public virtual bien_tipo_sujeto idTipoSujetoNavigation { get; set; }

    public virtual usuarios idUsuarioNavigation { get; set; }
}