// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class calificaciones_complementos_formacion
{
    public string idAlumno { get; set; }

    public int idComplemento { get; set; }

    public int idAsignatura { get; set; }

    public decimal? notaFinal { get; set; }

    public sbyte? aprobado { get; set; }
}