// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class calificaciones_grado
{
    public int idMatricula { get; set; }

    public int idAsignatura { get; set; }

    public decimal? nota { get; set; }

    public bool? aprobado { get; set; }

    public DateOnly? fecha_evaluacion { get; set; }
}