// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class calificaciones_conduccion
{
    public int? idmatricula { get; set; }

    public int? nota_final { get; set; }

    public bool? aprobado { get; set; }

    public string observacion { get; set; }
}