// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class calificaciones_propedeutico
{
    public string idAlumno { get; set; }

    public int idAsignatura { get; set; }

    public string idPeriodo { get; set; }

    public decimal? nota1 { get; set; }

    public sbyte? aprobado { get; set; }

    public string observacion { get; set; }
}