// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class cambiosmalla
{
    public int idCambioMalla { get; set; }

    public int idMalla { get; set; }

    public DateOnly? Fecha { get; set; }

    public string Cambio { get; set; }

    public virtual mallas idMallaNavigation { get; set; }
}