// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class campo_especifico_unesco
{
    public int idCampospecificoUnesco { get; set; }

    public int? idCampoAmplioUnesco { get; set; }

    public string nombreEspecifico { get; set; }

    public string codigoEspecifico { get; set; }

    public sbyte? activo { get; set; }

    public virtual ICollection<campo_detallado_unesco> campo_detallado_unesco { get; set; } = new List<campo_detallado_unesco>();

    public virtual campo_amplio_unesco idCampoAmplioUnescoNavigation { get; set; }
}