// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class cargo_instituto
{
    public int idCargoInstituto { get; set; }

    public int idTipoFuncionario { get; set; }

    public string nombre { get; set; }

    public int? disponibilidad_cargo { get; set; }

    public virtual tipo_funcionario idTipoFuncionarioNavigation { get; set; }
}