// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class carreras_adjuntos
{
    public int idCarrerasAdjuntos { get; set; }

    public int idCarrera { get; set; }

    public int idAdjuntos_Imagenes { get; set; }

    public virtual adjuntos_imagenes idAdjuntos_ImagenesNavigation { get; set; }

    public virtual carreras idCarreraNavigation { get; set; }
}