// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class categoria_contratos
{
    public int idCategoriaContratos { get; set; }

    public string nombre { get; set; }

    public virtual ICollection<escalafon> escalafon { get; set; } = new List<escalafon>();
}