// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class categorias_examenes_conduccion
{
    public int IdCategoria { get; set; }

    public string categoria { get; set; }

    public sbyte? tieneNota { get; set; }

    public sbyte? activa { get; set; }
}