// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class categorias_actividades
{
    public int idCategoria { get; set; }

    public string categoria { get; set; }

    public sbyte? esDocencia { get; set; }

    public sbyte? activo { get; set; }

    public sbyte? porcentaje { get; set; }

    public virtual ICollection<seddinstrumentos> seddinstrumentos { get; set; } = new List<seddinstrumentos>();

    public virtual ICollection<subcategorias_actividades> subcategorias_actividades { get; set; } = new List<subcategorias_actividades>();
}