// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class certificados_experiencia_laboral
{
    public int idcertificados_experiencia_laboral { get; set; }

    public string idProfesor { get; set; }

    public DateTime fecha_emision { get; set; }

    public sbyte generado_automaticamente { get; set; }

    public string ruta { get; set; }

    public sbyte esActivo { get; set; }

    public virtual profesores idProfesorNavigation { get; set; }
}