// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class ciudades
{
    public int idciudades { get; set; }

    public int idprovincias { get; set; }

    public string nombre { get; set; }

    public virtual provincias idprovinciasNavigation { get; set; }

    public virtual ICollection<parroquias> parroquias { get; set; } = new List<parroquias>();
}