// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class clausulas
{
    public int idClausulas { get; set; }

    public string nombre_clausula { get; set; }

    public int? orden { get; set; }

    public sbyte? esActivo { get; set; }

    public virtual ICollection<plantilla_clausulas> plantilla_clausulas { get; set; } = new List<plantilla_clausulas>();
}