// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class cliente_factura
{
    public string documentoFactura { get; set; }

    public string tipoDocumento { get; set; }

    public string nombre { get; set; }

    public string direccion { get; set; }

    public string telefono { get; set; }

    public string email { get; set; }

    public DateTime? fechaCreacion { get; set; }
}