// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class cond_alumnos_practicas
{
    public int idPractica { get; set; }

    public string idalumno { get; set; }

    public int idvehiculo { get; set; }

    public string idProfesor { get; set; }

    public string idPeriodo { get; set; }

    public string dia { get; set; }

    public DateOnly fecha { get; set; }

    public TimeOnly? hora_salida { get; set; }

    public TimeOnly? hora_llegada { get; set; }

    public TimeOnly? tiempo { get; set; }

    public bool? ensalida { get; set; }

    public bool? verificada { get; set; }

    public string user_asigna { get; set; }

    public string user_llegada { get; set; }

    public bool? cancelado { get; set; }

    public string observaciones { get; set; }
}