// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class cond_alumnos_horarios
{
    public int idAsignacionHorario { get; set; }

    public int idAsignacion { get; set; }

    public int idFecha { get; set; }

    public int idHora { get; set; }

    public sbyte? asiste { get; set; }

    public sbyte? activo { get; set; }

    public string observacion { get; set; }
}