// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

/// <summary>
/// conduccion — Auditoria de cambios de asistencia
/// </summary>
public partial class cond_acad_asistencias_historial
{
    public ulong idHistorial { get; set; }

    public int idAsistencia { get; set; }

    /// <summary>
    /// Desnormalizado: sobrevive al borrado en cascada
    /// </summary>
    public int idSesion { get; set; }

    /// <summary>
    /// Desnormalizado por el mismo motivo
    /// </summary>
    public int idMatricula { get; set; }

    /// <summary>
    /// NULL = alta inicial
    /// </summary>
    public string estadoAnterior { get; set; }

    public string estadoNuevo { get; set; }

    public string motivo { get; set; }

    /// <summary>
    /// usuarios.idSigafi tomado del JWT
    /// </summary>
    public string usuario { get; set; }

    /// <summary>
    /// cplec_docente | cplec_inspector
    /// </summary>
    public string rol { get; set; }

    public string ipAddress { get; set; }

    public DateTime fecha { get; set; }
}