// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

/// <summary>
/// conduccion — Asistencia por estudiante y sesion
/// </summary>
public partial class cond_acad_asistencias
{
    public int idAsistencia { get; set; }

    /// <summary>
    /// FK cplec_sesiones.idSesion
    /// </summary>
    public int idSesion { get; set; }

    /// <summary>
    /// FK matriculas.idMatricula
    /// </summary>
    public int idMatricula { get; set; }

    public string estado { get; set; }

    /// <summary>
    /// Solo aplica cuando estado = atraso
    /// </summary>
    public ushort? minutosAtraso { get; set; }

    public string observacion { get; set; }

    /// <summary>
    /// usuarios.idSigafi del autor
    /// </summary>
    public string usuarioCreacion { get; set; }

    public DateTime fechaCreacion { get; set; }

    public string usuarioActualiza { get; set; }

    public DateTime? fechaActualizacion { get; set; }

    public virtual matriculas idMatriculaNavigation { get; set; }

    public virtual cond_acad_sesiones idSesionNavigation { get; set; }
}