// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class cond_alumnos_vehiculos
{
    public int idAsignacion { get; set; }

    public string idAlumno { get; set; }

    public int idVehiculo { get; set; }

    public string idPeriodo { get; set; }

    public string idProfesor { get; set; }

    public DateTime fechaAsignacion { get; set; }

    public DateOnly? fechaInicio { get; set; }

    public DateOnly? fechaFin { get; set; }

    public sbyte? activa { get; set; }

    public string observacion { get; set; }
}