// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class cond_practicas_horarios_alumnos
{
    public int idPractica { get; set; }

    public int idAsignacionHorario { get; set; }
}