// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class configsharepoint
{
    public int idSharePoint { get; set; }

    public string ClientID { get; set; }

    public string TenanID { get; set; }

    public string ClientSecret { get; set; }

    public string AppID { get; set; }

    public string RedirectURL { get; set; }

    public string TenantName { get; set; }

    public string SiteName { get; set; }

    public string SiteID { get; set; }

    public string ListID { get; set; }

    public string DriveID { get; set; }

    public sbyte? esActivo { get; set; }

    public DateOnly? FechaCreado { get; set; }

    public DateOnly? FechaActualizado { get; set; }

    public string correo { get; set; }

    public string password { get; set; }
}