// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class contratos_facturas
{
    public int idFacturasContratos { get; set; }

    public int idContratos { get; set; }

    public DateOnly? periodoFactura { get; set; }

    public string numeroFactura { get; set; }

    public decimal? valorFacturado { get; set; }

    public virtual contratos idContratosNavigation { get; set; }
}