// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class credito_alumno_detalle
{
    public int idCreditoAlumnoDetalle { get; set; }

    public int? idCredito { get; set; }

    public DateOnly? fecha_pago { get; set; }

    public decimal? valorCuota { get; set; }

    public decimal? valorAbonado { get; set; }

    public sbyte? cancelado { get; set; }
}