// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class cron_tipo_proceso
{
    public int idTipoProceso { get; set; }

    public string detalle { get; set; }

    public bool? esInformativo { get; set; }

    public string audiencia { get; set; }

    public int? orden { get; set; }

    public bool? esActivo { get; set; }

    public virtual ICollection<cron_detalle_cronograma> cron_detalle_cronograma { get; set; } = new List<cron_detalle_cronograma>();
}