// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class cron_cronograma
{
    public int idCronograma { get; set; }

    public string idPeriodo { get; set; }

    public string detalle { get; set; }

    public bool? esPublico { get; set; }

    public bool? esActivo { get; set; }

    public virtual ICollection<cron_detalle_cronograma> cron_detalle_cronograma { get; set; } = new List<cron_detalle_cronograma>();

    public virtual ICollection<cron_dias_especiales> cron_dias_especiales { get; set; } = new List<cron_dias_especiales>();
}