// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class cron_dias_especiales
{
    public int idDiasEspeciales { get; set; }

    public DateTime? fecha { get; set; }

    public int idTipoDiaEspecial { get; set; }

    public int? idCronograma { get; set; }

    public bool? esRecuperable { get; set; }

    public virtual cron_cronograma idCronogramaNavigation { get; set; }

    public virtual cron_tipo_dia_especial idTipoDiaEspecialNavigation { get; set; }

    public virtual ICollection<vac_recuperacion_feriados> vac_recuperacion_feriados { get; set; } = new List<vac_recuperacion_feriados>();
}