// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class cron_tipo_dia_especial
{
    public int idTipoDiaEspecial { get; set; }

    public string detalle { get; set; }

    public bool? esFeriado { get; set; }

    public bool? esEventoInterno { get; set; }

    public DateOnly? fechaOriginal { get; set; }

    public virtual ICollection<cron_dias_especiales> cron_dias_especiales { get; set; } = new List<cron_dias_especiales>();
}