// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class cuentas
{
    public int idCuenta { get; set; }

    public string cuenta { get; set; }

    public string numero_cuenta { get; set; }

    public bool activo { get; set; }

    public byte esingreso { get; set; }

    public string tipo_pago { get; set; }
}