// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class cursos_profesores
{
    public int idCursoProfesor { get; set; }

    public string idProfesor { get; set; }

    public string nombre_curso { get; set; }

    public string Institucion { get; set; }

    public DateOnly? fecha_inicio { get; set; }

    public DateOnly? fecha_finalizacion { get; set; }

    public int? numero_horas { get; set; }

    public sbyte? esValido { get; set; }

    public string archivoCurso { get; set; }

    public sbyte? financioInstituto { get; set; }

    public virtual profesores idProfesorNavigation { get; set; }
}