// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class departamentossolicitudes
{
    public int idDepartamentoSolicitud { get; set; }

    public string departamento { get; set; }

    public sbyte? activo { get; set; }

    public virtual ICollection<tipossolicitudes> tipossolicitudes { get; set; } = new List<tipossolicitudes>();
}