// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class departamentos
{
    public int iddepartamentos { get; set; }

    public string nombre_departamento { get; set; }

    public string abreviacion { get; set; }

    public string descripcion { get; set; }

    public int? idInstitucion { get; set; }

    public virtual ICollection<ofertas_laborales> ofertas_laborales { get; set; } = new List<ofertas_laborales>();

    public virtual ICollection<vac_config_dias_extras_depto> vac_config_dias_extras_depto { get; set; } = new List<vac_config_dias_extras_depto>();
}