// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class detalle_sistema_evaluacion
{
    public string idperiodo { get; set; }

    public int idcarrera { get; set; }

    public int idsistemaevaluacion { get; set; }
}