// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class detalle_pagos
{
    public int idPago { get; set; }

    public int idEspecie { get; set; }

    public decimal? valor { get; set; }

    public decimal? descuento { get; set; }

    public int? idCredito { get; set; }

    public sbyte? migradoContabilidad { get; set; }

    public DateTime? fechaMigracion { get; set; }

    public virtual especies idEspecieNavigation { get; set; }

    public virtual pagos idPagoNavigation { get; set; }
}