// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class detalles_ofertas
{
    public int iddetalles_ofertas { get; set; }

    public int idofertas_laborales { get; set; }

    public int idjornadas_ofertas { get; set; }

    public int idmodalidades_ofertas { get; set; }

    public virtual jornadas_ofertas idjornadas_ofertasNavigation { get; set; }

    public virtual modalidades_ofertas idmodalidades_ofertasNavigation { get; set; }

    public virtual ofertas_laborales idofertas_laboralesNavigation { get; set; }
}