// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class detalles_documentos_pagos
{
    public uint iddocumentopago { get; set; }

    public int idpago { get; set; }

    public decimal valor { get; set; }

    public virtual pagos idpagoNavigation { get; set; }
}