// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class documentos_adjuntos
{
    public int iddocumentos_adjuntos { get; set; }

    public string idAlumno { get; set; }

    public int idtipos_documentos { get; set; }

    public string nombre_archivo { get; set; }

    public string ruta_archivo { get; set; }

    public DateTime? fecha_Subida { get; set; }

    public DateTime? fecha_modificacion { get; set; }

    public virtual tipos_documentos idtipos_documentosNavigation { get; set; }

    public virtual ICollection<postulaciones> postulaciones { get; set; } = new List<postulaciones>();
}