// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class ed_encuestas
{
    public int idEncuesta { get; set; }

    public string nombre { get; set; }

    public string descripcion { get; set; }

    public sbyte? activo { get; set; }
}