// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class ed_fechasevaluacion
{
    public string idPeriodo { get; set; }

    public int idModalidad { get; set; }

    public DateOnly? fecha_inicio { get; set; }

    public DateOnly? fecha_final { get; set; }
}