// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class ed_preguntas
{
    public int IdPregunta { get; set; }

    public int? idEncuesta { get; set; }

    public string pregunta { get; set; }

    public int? orden { get; set; }

    public sbyte? activa { get; set; }

    public sbyte? esAbierta { get; set; }
}