// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class ed_respuestastestab
{
    public int idIngresoTest { get; set; }

    public int idPregunta { get; set; }

    public string respuesta { get; set; }
}