// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class empresas_contactos
{
    public int idempresas_contactos { get; set; }

    public string idempresa { get; set; }

    public int idtipo_contacto { get; set; }

    public string valor { get; set; }

    public DateOnly? fecha_creacion { get; set; }

    public DateOnly? fecha_modificacion { get; set; }

    public virtual empresas idempresaNavigation { get; set; }

    public virtual tipo_contacto idtipo_contactoNavigation { get; set; }
}