// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class espacios
{
    public int idEspacio { get; set; }

    public string codigo { get; set; }

    public string nombre { get; set; }

    public string tipo { get; set; }

    public int capacidad { get; set; }

    public int? idCarrera { get; set; }

    public string edificio { get; set; }

    public int piso { get; set; }

    public sbyte activo { get; set; }

    public sbyte? requiereReserva { get; set; }

    public string imagen_referencia { get; set; }

    public sbyte esAsincrono { get; set; }

    public virtual ICollection<horario_detalle> horario_detalle { get; set; } = new List<horario_detalle>();

    public virtual carreras idCarreraNavigation { get; set; }
}