// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class especies_extras
{
    public int idmatricula { get; set; }

    public int idespecie { get; set; }

    public DateOnly fecha_registro { get; set; }

    public decimal valor { get; set; }

    public DateOnly fecha_limite_pago { get; set; }

    public string observacion { get; set; }

    public bool obligatoria { get; set; }

    public decimal pagado { get; set; }

    public bool extra { get; set; }

    public string tipo { get; set; }
}