// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class especies
{
    public int idEspecie { get; set; }

    public string especie { get; set; }

    public decimal valor { get; set; }

    public int numero_cuotas { get; set; }

    public int? prioridad { get; set; }

    public sbyte? permite_intercalar { get; set; }

    public string codigo_referencia { get; set; }

    public string idperiodo { get; set; }

    public decimal? extraordinaria { get; set; }

    public int? idNivel { get; set; }

    public virtual ICollection<detalle_pagos> detalle_pagos { get; set; } = new List<detalle_pagos>();
}