// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class extras_contratos
{
    public int idExtraContratos { get; set; }

    public int idContratos { get; set; }

    public DateOnly? fecha_registro { get; set; }

    public DateOnly? fecha_inicioextra { get; set; }

    public decimal? valor_extra { get; set; }

    public string motivo { get; set; }

    public DateOnly? fecha_finalizacion { get; set; }

    public sbyte? esactivo { get; set; }

    public string usuarioRegistra { get; set; }

    public virtual contratos idContratosNavigation { get; set; }
}