// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class fechas_pagos
{
    public int idFecha { get; set; }

    public int? idEspecie { get; set; }

    public DateOnly? fecha { get; set; }
}