// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class fechas_grados
{
    public string idperiodo { get; set; }

    public int idnivel { get; set; }

    public int idseccion { get; set; }

    public string paralelo { get; set; }

    public DateOnly? fecha_grado { get; set; }
}