// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class fechas_horarios
{
    public int idFecha { get; set; }

    public DateOnly? fecha { get; set; }

    public sbyte? finsemana { get; set; }

    public string dia { get; set; }

    public virtual ICollection<cond_acad_sesiones> cond_acad_sesiones { get; set; } = new List<cond_acad_sesiones>();

    public virtual ICollection<fechas_semanas> fechas_semanas { get; set; } = new List<fechas_semanas>();

    public virtual ICollection<horario_detalle> horario_detalle { get; set; } = new List<horario_detalle>();
}