// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class fechas_semanas
{
    public int idFechasSemanas { get; set; }

    public int idSemanasHorarios { get; set; }

    public int idFecha { get; set; }

    public string idPeriodo { get; set; }

    public virtual fechas_horarios idFechaNavigation { get; set; }

    public virtual periodos idPeriodoNavigation { get; set; }

    public virtual semanas_horarios idSemanasHorariosNavigation { get; set; }
}