// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class fechas_pagos_cuotas
{
    public int idFecha { get; set; }

    public string idPeriodo { get; set; }

    public int idModalidad { get; set; }

    public int idCarrera { get; set; }

    public string codigo_referencia { get; set; }

    public DateOnly? fecha { get; set; }

    public decimal? valorCuota { get; set; }

    public sbyte? genera_fecha { get; set; }

    public sbyte? activo { get; set; }

    public virtual carreras idCarreraNavigation { get; set; }

    public virtual modalidades idModalidadNavigation { get; set; }

    public virtual periodos idPeriodoNavigation { get; set; }
}