// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class gest_password_resets
{
    public int idToken { get; set; }

    public int idUsuario { get; set; }

    public string tokenHash { get; set; }

    public DateTime fechaCreacion { get; set; }

    public DateTime fechaExpiracion { get; set; }

    public sbyte usado { get; set; }

    public string ipSolicitud { get; set; }

    public virtual usuarios idUsuarioNavigation { get; set; }
}