// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class gest_audit_acciones
{
    public string idAuditAcciones { get; set; }

    public string codigoSistema { get; set; }

    public string idModulo { get; set; }

    public string nombre { get; set; }

    public string descripcion { get; set; }

    public sbyte? esActivo { get; set; }
}