// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class grados_academicos
{
    public int idGradoAcademico { get; set; }

    public int idNivelAcademico { get; set; }

    public string nombre { get; set; }

    public virtual niveles_academicos idNivelAcademicoNavigation { get; set; }

    public virtual ICollection<titulos_en_curso> titulos_en_curso { get; set; } = new List<titulos_en_curso>();

    public virtual ICollection<titulos_profesores> titulos_profesores { get; set; } = new List<titulos_profesores>();
}