// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class habilidades
{
    public int idhabilidades { get; set; }

    public string nombre { get; set; }

    public string descripcion { get; set; }

    public virtual ICollection<alumnos_habilidades> alumnos_habilidades { get; set; } = new List<alumnos_habilidades>();

    public virtual ICollection<habilidades_requeridas> habilidades_requeridas { get; set; } = new List<habilidades_requeridas>();
}