// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class horario_profesores
{
    public int idHorario { get; set; }

    public int? idAsignacion { get; set; }

    public int? idHora { get; set; }

    public int? idFecha { get; set; }

    public sbyte? asiste { get; set; }

    public sbyte? activo { get; set; }
}