// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class horario_detalle
{
    public int idHorario { get; set; }

    public int idAsignacion { get; set; }

    public int idFecha { get; set; }

    public int idhora { get; set; }

    public int? idEspacio { get; set; }

    public string tipoBloque { get; set; }

    public sbyte? activo { get; set; }

    public sbyte? claseReasignacion { get; set; }

    public bool? esRecuperacionPedagocia { get; set; }

    public string observacion { get; set; }

    public int? idHorarioReasgincacion { get; set; }

    public virtual asignaciones_profesores idAsignacionNavigation { get; set; }

    public virtual espacios idEspacioNavigation { get; set; }

    public virtual fechas_horarios idFechaNavigation { get; set; }

    public virtual horas_clases idhoraNavigation { get; set; }
}