// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class instituciones
{
    public int idInstitucion { get; set; }

    public string Institucion { get; set; }

    public string ciudad { get; set; }

    public string provincia { get; set; }
}