// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class logsmigraciones
{
    public int idLog { get; set; }

    public string status { get; set; }

    public DateTime? fecha { get; set; }
}