// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class mallas_periodos
{
    public string idPeriodo { get; set; }

    public int idNivel { get; set; }

    public int idMalla { get; set; }
}