// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class matriculas
{
    public int idMatricula { get; set; }

    public string idAlumno { get; set; }

    public int idNivel { get; set; }

    public int idSeccion { get; set; }

    public int idModalidad { get; set; }

    public string idPeriodo { get; set; }

    public DateTime? fechaMatricula { get; set; }

    public string paralelo { get; set; }

    public bool? arrastres { get; set; }

    public int? folio { get; set; }

    public decimal? beca_matricula { get; set; }

    public decimal? beca_colegiatura { get; set; }

    public bool? retirado { get; set; }

    public DateOnly? fechaRetiro { get; set; }

    public string observacion { get; set; }

    public bool? convalidacion { get; set; }

    public string carrera_convalidada { get; set; }

    public int? numero_permiso { get; set; }

    public string user_matricula { get; set; }

    public sbyte? valida { get; set; }

    public sbyte? esOyente { get; set; }

    public string documentoFactura { get; set; }

    public virtual ICollection<bien_apoyo_financiero> bien_apoyo_financiero { get; set; } = new List<bien_apoyo_financiero>();

    public virtual ICollection<bien_postulaciones_becas> bien_postulaciones_becas { get; set; } = new List<bien_postulaciones_becas>();

    public virtual ICollection<calificaciones> calificaciones { get; set; } = new List<calificaciones>();

    public virtual ICollection<cond_acad_asistencias> cond_acad_asistencias { get; set; } = new List<cond_acad_asistencias>();

    public virtual alumnos idAlumnoNavigation { get; set; }

    public virtual modalidades idModalidadNavigation { get; set; }

    public virtual cursos idNivelNavigation { get; set; }

    public virtual periodos idPeriodoNavigation { get; set; }

    public virtual secciones idSeccionNavigation { get; set; }

    public virtual ICollection<solicitudescalificaciones> solicitudescalificaciones { get; set; } = new List<solicitudescalificaciones>();

    public virtual ICollection<vinculacionproyectosalumnos> vinculacionproyectosalumnos { get; set; } = new List<vinculacionproyectosalumnos>();
}