// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class matriculas_examen_conduccion
{
    public int idMatricula { get; set; }

    public int idCategoria { get; set; }

    public int? nota { get; set; }

    public string observacion { get; set; }

    public string usuario { get; set; }

    public DateOnly? fechaExamen { get; set; }

    public DateTime fechaIngreso { get; set; }

    public string instructor { get; set; }
}