// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class medios_contacto
{
    public int idMedio { get; set; }

    public string medio { get; set; }

    public ulong? activo { get; set; }
}