// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class modalidades_carreras
{
    public int idModalidadCarrera { get; set; }

    public int idCarrera { get; set; }

    public int idModalidad { get; set; }

    public sbyte? esActivo { get; set; }

    public virtual carreras idCarreraNavigation { get; set; }

    public virtual modalidades idModalidadNavigation { get; set; }
}