// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class modalidades_ofertas
{
    public int idmodalidades_ofertas { get; set; }

    public string tipo_modalidad { get; set; }

    public virtual ICollection<detalles_ofertas> detalles_ofertas { get; set; } = new List<detalles_ofertas>();
}