// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class nacionalidades
{
    public int idNacionalidad { get; set; }

    public string nacionalidad { get; set; }

    public sbyte? esNinguna { get; set; }

    public virtual ICollection<profesores> profesores { get; set; } = new List<profesores>();
}