// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class niveles_academicos
{
    public int idNivelAcademico { get; set; }

    public string nombre { get; set; }

    public virtual ICollection<grados_academicos> grados_academicos { get; set; } = new List<grados_academicos>();
}