// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class ofertas_carreras
{
    public int idofertas_carreras { get; set; }

    public int idofertas_laborales { get; set; }

    public int idCarrera { get; set; }

    public virtual carreras idCarreraNavigation { get; set; }

    public virtual ofertas_laborales idofertas_laboralesNavigation { get; set; }
}