// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class ofertas_requisitos
{
    public int idofertas_requisitos { get; set; }

    public int idofertas_laborales { get; set; }

    public string descripcion { get; set; }

    public sbyte? es_obligatoria { get; set; }

    public virtual ofertas_laborales idofertas_laboralesNavigation { get; set; }
}