// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class parciales
{
    public int idParcial { get; set; }

    public string Parcial { get; set; }

    public DateOnly? fecha_inicio { get; set; }

    public DateOnly? fecha_final { get; set; }

    public sbyte? esPrimero { get; set; }

    public sbyte? esSegundo { get; set; }

    public sbyte? esExamenFinal { get; set; }

    public sbyte? esRemedial { get; set; }

    public virtual ICollection<solicitudescalificaciones> solicitudescalificaciones { get; set; } = new List<solicitudescalificaciones>();
}