// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class parciales_modalidades_fechas
{
    public string idPeriodo { get; set; }

    public int? idParcial { get; set; }

    public int? idModalidad { get; set; }

    public DateOnly? fechaInicio { get; set; }

    public DateOnly? fechaFin { get; set; }

    public sbyte? activo { get; set; }
}