// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class parroquias
{
    public int idParroquias { get; set; }

    public int idciudades { get; set; }

    public string nombre { get; set; }

    public virtual ICollection<alumnos> alumnos { get; set; } = new List<alumnos>();

    public virtual ciudades idciudadesNavigation { get; set; }

    public virtual ICollection<profesores> profesoresidParroquiaNacimientoNavigation { get; set; } = new List<profesores>();

    public virtual ICollection<profesores> profesoresidParroquiaResidenciaNavigation { get; set; } = new List<profesores>();
}