// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class pd_aceptaciones_usuarios
{
    public int idAceptacionUsuario { get; set; }

    public string idUsuario { get; set; }

    public int? idTermino { get; set; }

    public string sistema { get; set; }

    public DateTime? fechaRegistro { get; set; }

    public string ipOrigen { get; set; }

    public string dispositivo { get; set; }
}