// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class pd_categorias_terminos_condiciones
{
    public int idCategoria { get; set; }

    public string categoria { get; set; }

    public sbyte? esAlumno { get; set; }

    public sbyte? esDocente { get; set; }

    public sbyte? esAdministrativo { get; set; }

    public sbyte? esExterno { get; set; }

    public DateOnly? fechaRegistro { get; set; }

    public sbyte? activo { get; set; }
}