// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class pd_terminos_condiciones
{
    public int idTermino { get; set; }

    public int? idCategoria { get; set; }

    public string versionTermino { get; set; }

    public string contenido { get; set; }

    public DateOnly? fechaPublicacion { get; set; }

    public DateTime fechaRegistro { get; set; }

    public string archivoHtml { get; set; }

    public sbyte? esVigente { get; set; }
}