// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class periodos_inscripciones
{
    public int idPeriodoInscripcion { get; set; }

    public string idPeriodo { get; set; }

    public int? idModalidad { get; set; }

    public int? idNivel { get; set; }

    public int? idSeccion { get; set; }

    public DateOnly? fechaInicio { get; set; }

    public DateOnly? fechaFinal { get; set; }

    public DateTime fechaRegistro { get; set; }

    public sbyte? activo { get; set; }

    public sbyte? conduccion { get; set; }
}