// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class periodos_matriculas_niveles
{
    public string idPeriodo { get; set; }

    public int idNivel { get; set; }

    public int idSeccion { get; set; }

    public sbyte? activo { get; set; }
}