// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class plantilla_clausulas
{
    public int idPlantillasClausulas { get; set; }

    public int idPlantillaContrato { get; set; }

    public int idClausulas { get; set; }

    public string texto { get; set; }

    public int? orden { get; set; }

    public DateOnly? fecha_creacion { get; set; }

    public DateOnly? fecha_modificacion { get; set; }

    public sbyte? esActivo { get; set; }

    public virtual clausulas idClausulasNavigation { get; set; }

    public virtual plantilla_contrato idPlantillaContratoNavigation { get; set; }
}