// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class prerequisitos
{
    public int idDetalleMalla { get; set; }

    public int idAsignatura { get; set; }

    public sbyte? activa { get; set; }

    public virtual asignaturas idAsignaturaNavigation { get; set; }

    public virtual detallemallas idDetalleMallaNavigation { get; set; }
}