// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class procesos_usuario
{
    public string proceso { get; set; }

    public string usuario { get; set; }

    public sbyte? consultar { get; set; }

    public sbyte? insertar { get; set; }

    public sbyte? modificar { get; set; }

    public sbyte? eliminar { get; set; }
}