// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class profesores_motivo_salida
{
    public string idProfesor { get; set; }

    public int idMotivoSalida { get; set; }

    public int idContratos { get; set; }

    public string Observacion { get; set; }

    public string ruta_archivo { get; set; }

    public DateOnly? fecha_registro { get; set; }

    public DateOnly? fecha_salida { get; set; }

    public virtual contratos idContratosNavigation { get; set; }

    public virtual motivo_salida idMotivoSalidaNavigation { get; set; }

    public virtual profesores idProfesorNavigation { get; set; }
}