// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class profesores_actividades
{
    public string idPeriodo { get; set; }

    public string idProfesor { get; set; }

    public int idSubcategoria { get; set; }

    public int? horas_semana { get; set; }

    public string usuario { get; set; }

    public DateTime? fecha { get; set; }

    public virtual subcategorias_actividades idSubcategoriaNavigation { get; set; }
}