// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

/// <summary>
/// Tramos laborales por reingresos; base del ciclo vacacional actual
/// </summary>
public partial class profesores_historial_laboral
{
    public int id_historial { get; set; }

    public string id_profesor { get; set; }

    public DateOnly fecha_ingreso { get; set; }

    /// <summary>
    /// NULL = tramo vigente
    /// </summary>
    public DateOnly? fecha_retiro { get; set; }

    public bool es_tramo_actual { get; set; }

    public string motivo_salida { get; set; }

    /// <summary>
    /// Contrato asociado al tramo si existe
    /// </summary>
    public int? id_contratos { get; set; }

    public string observacion { get; set; }

    public int? registrado_por_id { get; set; }

    public DateTime fecha_registro { get; set; }

    public virtual profesores id_profesorNavigation { get; set; }
}