// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class profesores_dedicacion
{
    public int idProfesoresDedicacion { get; set; }

    public string idProfesor { get; set; }

    public int idDedicacionCategorias { get; set; }

    public string idPeriodo { get; set; }

    public sbyte? esActivo { get; set; }

    public virtual dedicacion_categorias idDedicacionCategoriasNavigation { get; set; }

    public virtual periodos idPeriodoNavigation { get; set; }

    public virtual profesores idProfesorNavigation { get; set; }
}