// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class profesores_carreras_periodos
{
    public int idProfesoresCarrerasPeriodos { get; set; }

    public string idPeriodo { get; set; }

    public string idProfesor { get; set; }

    public int? idCarrera { get; set; }

    public sbyte? esActivo { get; set; }

    public sbyte? sonTodas { get; set; }

    public virtual carreras idCarreraNavigation { get; set; }

    public virtual periodos idPeriodoNavigation { get; set; }

    public virtual profesores idProfesorNavigation { get; set; }
}