// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class provincias
{
    public int idprovincias { get; set; }

    public int idpaises { get; set; }

    public string nombre { get; set; }

    public virtual ICollection<ciudades> ciudades { get; set; } = new List<ciudades>();

    public virtual paises idpaisesNavigation { get; set; }
}