// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class rbac_operaciones
{
    public int idOperaciones { get; set; }

    public string NombreOperacion { get; set; }

    public virtual ICollection<rbac_modulos_operaciones> rbac_modulos_operaciones { get; set; } = new List<rbac_modulos_operaciones>();
}