// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class rbac_sistema
{
    public int idSistema { get; set; }

    public string codigo { get; set; }

    public string detalle { get; set; }

    public string url { get; set; }

    public string icono { get; set; }

    public virtual ICollection<rbac_modulos> rbac_modulos { get; set; } = new List<rbac_modulos>();
}