// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class relacion_ies
{
    public int idRelacionIes { get; set; }

    public string nombre { get; set; }
}