// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class restricciones
{
    public string idrestriccion { get; set; }

    public string restriccion { get; set; }

    public ulong? activo { get; set; }
}