// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class sectores_empresas
{
    public int idsectores_empresas { get; set; }

    public string nombre_sector { get; set; }

    public string codigo_sector { get; set; }

    public virtual ICollection<empresas> empresas { get; set; } = new List<empresas>();
}