// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class seddautoridadescarrerasperiodos
{
    public int idAsignacion { get; set; }

    public int? idCarrera { get; set; }

    public string idPeriodo { get; set; }

    public string idProfesor { get; set; }

    public int? idInstrumento { get; set; }

    public string designacion { get; set; }

    public sbyte? activo { get; set; }
}