// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class seddautoevaluacion
{
    public int idTest { get; set; }

    public int? idInstrumento { get; set; }

    public string idPeriodo { get; set; }

    public string idProfesor { get; set; }

    public DateTime fechaRegistro { get; set; }

    public virtual seddinstrumentos idInstrumentoNavigation { get; set; }

    public virtual ICollection<sedddetalleautoevaluacion> sedddetalleautoevaluacion { get; set; } = new List<sedddetalleautoevaluacion>();
}