// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class sedddetallecoevaluacion
{
    public int idDetalle { get; set; }

    public int? idTest { get; set; }

    public int? idPregunta { get; set; }

    public int? respuesta { get; set; }

    public virtual seddpreguntas idPreguntaNavigation { get; set; }

    public virtual seddcoevaluacion idTestNavigation { get; set; }
}