// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class seedevaluadoresinsitu
{
    public int idAsignacionEvaluador { get; set; }

    public string idPeriodo { get; set; }

    public string idEvaluador { get; set; }

    public string idProfesor { get; set; }

    public DateTime? fechaRegistro { get; set; }

    public sbyte? activo { get; set; }
}