// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class sistema_titulacion
{
    public int codigo_sistema { get; set; }

    public string detalle { get; set; }

    public sbyte? activo { get; set; }
}