// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class solicitudeslogs
{
    public int idLogSolicitud { get; set; }

    public int? idSolicitud { get; set; }

    public DateTime? fechaRegistro { get; set; }

    public string detalle { get; set; }

    public int? idRespuestaSolicitud { get; set; }
}