// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class subcategorias_actividades
{
    public int idSubcategoria { get; set; }

    public int? idCategoria { get; set; }

    public string subcategoria { get; set; }

    public sbyte? esDocencia { get; set; }

    public sbyte? activa { get; set; }

    public virtual categorias_actividades idCategoriaNavigation { get; set; }

    public virtual ICollection<profesores_actividades> profesores_actividades { get; set; } = new List<profesores_actividades>();
}