// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class subcategoria_vehiculos
{
    public int idSubcategoria { get; set; }

    public string subcategoria { get; set; }

    public sbyte? activa { get; set; }
}