// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class sueldos_contratos
{
    public int idSueldosContratos { get; set; }

    public int idContratos { get; set; }

    public DateOnly? fecha_registro { get; set; }

    public DateOnly? fecha_cambiosueldo { get; set; }

    public decimal? sueldo { get; set; }

    public sbyte? esactivo { get; set; }

    public string usarioRegistra { get; set; }

    public virtual contratos idContratosNavigation { get; set; }
}