// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class tiposdocumentosi
{
    public string tipoDocumento { get; set; }

    public string documento { get; set; }

    public sbyte? activo { get; set; }
}