// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class tipo_funcionario
{
    public int idTipoFuncionario { get; set; }

    public string nombre { get; set; }

    public ulong? esDocente { get; set; }

    public virtual ICollection<cargo_instituto> cargo_instituto { get; set; } = new List<cargo_instituto>();
}