// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class tipos_contratos
{
    public int idTiposContratos { get; set; }

    public string nombre { get; set; }

    public string codigo { get; set; }

    public int? duracionSemanas { get; set; }

    public ulong? esAfiliado { get; set; }

    public virtual ICollection<plantilla_contrato> plantilla_contrato { get; set; } = new List<plantilla_contrato>();
}