// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class tiposangre
{
    public string codigoTipoSangre { get; set; }

    public string grupo { get; set; }

    public sbyte? sitemaRH { get; set; }

    public virtual ICollection<profesores> profesores { get; set; } = new List<profesores>();
}