// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class tipo_contacto
{
    public int idtipo_contacto { get; set; }

    public string nombre_contacto { get; set; }

    public string longitud_contacto { get; set; }

    public virtual ICollection<empresas_contactos> empresas_contactos { get; set; } = new List<empresas_contactos>();
}