// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class titulos_profesores
{
    public int idTitulosProfesor { get; set; }

    public string idProfesor { get; set; }

    public string titulo { get; set; }

    public int idUniversidad { get; set; }

    public int idGradoAcademico { get; set; }

    public string codigo_senescyt { get; set; }

    public DateOnly? fecha_obtencion { get; set; }

    public DateOnly? fecha_registro { get; set; }

    public int idCampoDetalladoUnesco { get; set; }

    public string archivoTitulo { get; set; }

    public virtual campo_detallado_unesco idCampoDetalladoUnescoNavigation { get; set; }

    public virtual grados_academicos idGradoAcademicoNavigation { get; set; }

    public virtual profesores idProfesorNavigation { get; set; }

    public virtual universidades idUniversidadNavigation { get; set; }
}