// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class titulos
{
    public int idTitulo { get; set; }

    public string titulo { get; set; }

    public string titulo_femenino { get; set; }

    public int? nivel_inicial { get; set; }

    public int? nivel_final { get; set; }

    public int? idCarrera { get; set; }

    public sbyte? tiene_practicas { get; set; }

    public int? creditos_practicas { get; set; }

    public sbyte? tiene_titulacion { get; set; }

    public int? creditos_titulacion { get; set; }
}