// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class usuarios_web
{
    public string usuario { get; set; }

    public string password { get; set; }

    public sbyte? salida { get; set; }

    public sbyte? ingreso { get; set; }

    public sbyte? activo { get; set; }

    public sbyte? asistencia { get; set; }

    public sbyte? esRrhh { get; set; }
}