// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class usuarios
{
    public int idUsuario { get; set; }

    /// <summary>
    /// este es idSifafi\n
    /// </summary>
    public string idSigafi { get; set; }

    public string tablaSigafi { get; set; }

    public string nombre { get; set; }

    public string contrasenia { get; set; }

    public sbyte activo { get; set; }

    public sbyte administrador { get; set; }

    public string emailInstitucional { get; set; }

    public sbyte emailValidado { get; set; }

    public string hashEmailToken { get; set; }

    public DateTime? fechaEmailValidacion { get; set; }

    public virtual ICollection<bien_apoyo_financiero> bien_apoyo_financiero { get; set; } = new List<bien_apoyo_financiero>();

    public virtual ICollection<bien_caso> bien_caso { get; set; } = new List<bien_caso>();

    public virtual ICollection<bien_caso_desarrollo> bien_caso_desarrollo { get; set; } = new List<bien_caso_desarrollo>();

    public virtual ICollection<bien_caso_requerimiento> bien_caso_requerimiento { get; set; } = new List<bien_caso_requerimiento>();

    public virtual ICollection<bien_postulacion_requisitos_becas> bien_postulacion_requisitos_becas { get; set; } = new List<bien_postulacion_requisitos_becas>();

    public virtual ICollection<bien_postulaciones_becas> bien_postulaciones_becas { get; set; } = new List<bien_postulaciones_becas>();

    public virtual ICollection<bien_resoluciones_tribunales> bien_resoluciones_tribunales { get; set; } = new List<bien_resoluciones_tribunales>();

    public virtual bien_tribunal bien_tribunal { get; set; }

    public virtual ICollection<bien_usuario_caso> bien_usuario_caso { get; set; } = new List<bien_usuario_caso>();

    public virtual ICollection<gest_password_resets> gest_password_resets { get; set; } = new List<gest_password_resets>();

    public virtual ICollection<kardex_vacaciones> kardex_vacaciones { get; set; } = new List<kardex_vacaciones>();

    public virtual ICollection<rbac_refresh_tokens> rbac_refresh_tokens { get; set; } = new List<rbac_refresh_tokens>();

    public virtual ICollection<rbac_usuario_rol> rbac_usuario_rol { get; set; } = new List<rbac_usuario_rol>();

    public virtual ICollection<solicitudes_licencias> solicitudes_licencias { get; set; } = new List<solicitudes_licencias>();

    public virtual ICollection<vac_cierres_colectivos> vac_cierres_colectivos { get; set; } = new List<vac_cierres_colectivos>();

    public virtual ICollection<vac_ledger> vac_ledger { get; set; } = new List<vac_ledger>();

    public virtual ICollection<vac_periodos_vacacionales> vac_periodos_vacacionalesusuario_rlNavigation { get; set; } = new List<vac_periodos_vacacionales>();

    public virtual ICollection<vac_periodos_vacacionales> vac_periodos_vacacionalesusuario_thNavigation { get; set; } = new List<vac_periodos_vacacionales>();

    public virtual ICollection<vac_permisos> vac_permisos { get; set; } = new List<vac_permisos>();

    public virtual ICollection<vac_recuperacion_feriados> vac_recuperacion_feriados { get; set; } = new List<vac_recuperacion_feriados>();

    public virtual ICollection<vac_recuperacion_tiempo> vac_recuperacion_tiempo { get; set; } = new List<vac_recuperacion_tiempo>();
}