// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vac_plantillas_documentos
{
    public int id_plantilla { get; set; }

    public string codigo { get; set; }

    public string nombre { get; set; }

    public string cuerpo { get; set; }

    public bool? activo { get; set; }

    public DateTime fecha_actualizacion { get; set; }
}