// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vac_cierres_colectivos
{
    public int id_cierre { get; set; }

    public string nombre { get; set; }

    public DateOnly fecha_inicio { get; set; }

    public DateOnly fecha_fin { get; set; }

    public decimal dias_descuento { get; set; }

    public int fines_semana_incluidos { get; set; }

    public DateTime fecha_creacion { get; set; }

    public int registrado_por_id { get; set; }

    public virtual usuarios registrado_por { get; set; }

    public virtual ICollection<vac_cierres_colectivos_exclusiones> vac_cierres_colectivos_exclusiones { get; set; } = new List<vac_cierres_colectivos_exclusiones>();
}