// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vac_config_dias_extras_excepciones
{
    public int id_excepcion { get; set; }

    public int id_config { get; set; }

    public string id_profesor { get; set; }

    public string tipo { get; set; }

    public virtual vac_config_dias_extras_depto id_configNavigation { get; set; }

    public virtual profesores id_profesorNavigation { get; set; }
}