// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vac_recuperacion_tiempo
{
    public int id_recuperacion { get; set; }

    public int id_permiso { get; set; }

    public DateOnly fecha_recuperada { get; set; }

    public decimal horas_recuperadas { get; set; }

    public DateTime fecha_registro { get; set; }

    public int usuario_th { get; set; }

    public virtual vac_permisos id_permisoNavigation { get; set; }

    public virtual usuarios usuario_thNavigation { get; set; }
}