// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vac_permisos
{
    public int id_permiso { get; set; }

    public string id_profesor { get; set; }

    public int id_tipo_permiso { get; set; }

    public decimal? horas_solicitadas { get; set; }

    public int? dias_solicitados { get; set; }

    public string estado { get; set; }

    public DateOnly fecha_suceso { get; set; }

    public DateTime fecha_solicitud { get; set; }

    public string motivo { get; set; }

    public string ruta_justificativo { get; set; }

    public DateTime? fecha_entrega_justificativo { get; set; }

    public int? aprobado_por_id { get; set; }

    public string notas_rrhh { get; set; }

    public bool afecta_vacaciones { get; set; }

    public bool adjunto_pendiente_fisico { get; set; }

    public virtual usuarios aprobado_por { get; set; }

    public virtual profesores id_profesorNavigation { get; set; }

    public virtual vac_tipos_permisos id_tipo_permisoNavigation { get; set; }

    public virtual ICollection<vac_ledger> vac_ledger { get; set; } = new List<vac_ledger>();

    public virtual ICollection<vac_recuperacion_tiempo> vac_recuperacion_tiempo { get; set; } = new List<vac_recuperacion_tiempo>();
}