// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vac_saldos
{
    public int id_saldo_vacaciones { get; set; }

    public string id_profesor { get; set; }

    public string periodo { get; set; }

    public decimal dias_ganados { get; set; }

    public decimal dias_tomados { get; set; }

    public decimal dias_acumulados { get; set; }

    public int fines_semana_tomados { get; set; }

    public DateOnly fecha_ultimo_calculo { get; set; }

    public bool? activo { get; set; }

    public virtual profesores id_profesorNavigation { get; set; }
}