// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vac_recuperacion_feriados
{
    public int id_recuperacion_feriado { get; set; }

    public int id_dias_especiales { get; set; }

    public string id_profesor { get; set; }

    public DateOnly fecha_recuperacion { get; set; }

    public bool completado { get; set; }

    public string observacion { get; set; }

    public int? registrado_por_id { get; set; }

    public virtual cron_dias_especiales id_dias_especialesNavigation { get; set; }

    public virtual profesores id_profesorNavigation { get; set; }

    public virtual usuarios registrado_por { get; set; }
}