// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vac_periodos_vacacionales
{
    public int id_periodo_vacaciones { get; set; }

    public string id_profesor { get; set; }

    public string origen_evento { get; set; }

    public string periodo_lectivo { get; set; }

    public DateOnly fecha_inicio { get; set; }

    public DateOnly fecha_fin { get; set; }

    public int dias_solicitados { get; set; }

    public int cant_fines_semana { get; set; }

    public bool es_fuera_planificacion { get; set; }

    public string estado { get; set; }

    public DateTime fecha_solicitud { get; set; }

    public string ruta_documento { get; set; }

    public int? usuario_th { get; set; }

    public DateTime? fecha_aprobacion_th { get; set; }

    public int? usuario_rl { get; set; }

    public DateTime? fecha_aprobacion_rl { get; set; }

    public string motivo_solicitud { get; set; }

    public string motivo_rechazo { get; set; }

    public bool requiere_fin_semana { get; set; }

    public int? cant_fines_semana_requeridos { get; set; }

    public virtual profesores id_profesorNavigation { get; set; }

    public virtual usuarios usuario_rlNavigation { get; set; }

    public virtual usuarios usuario_thNavigation { get; set; }

    public virtual ICollection<vac_ledger> vac_ledger { get; set; } = new List<vac_ledger>();
}