// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vac_cierres_colectivos_exclusiones
{
    public int id_exclusion { get; set; }

    public int id_cierre { get; set; }

    public string id_profesor { get; set; }

    public virtual vac_cierres_colectivos id_cierreNavigation { get; set; }

    public virtual profesores id_profesorNavigation { get; set; }
}