// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vac_config_dias_extras_depto
{
    public int id_config { get; set; }

    public int iddepartamentos { get; set; }

    public int? id_institucion { get; set; }

    public decimal dias_extras { get; set; }

    public bool requiere_fin_semana { get; set; }

    public int? cant_fines_semana_requeridos { get; set; }

    public string periodo_aplicacion { get; set; }

    public bool? activo { get; set; }

    public string motivo { get; set; }

    public DateOnly? fecha_vigencia_desde { get; set; }

    public DateOnly? fecha_vigencia_hasta { get; set; }

    public int? registrado_por_id { get; set; }

    public DateTime fecha_creacion { get; set; }

    public virtual departamentos iddepartamentosNavigation { get; set; }

    public virtual ICollection<vac_config_dias_extras_excepciones> vac_config_dias_extras_excepciones { get; set; } = new List<vac_config_dias_extras_excepciones>();
}