// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vac_ledger
{
    public int id_ledger { get; set; }

    public string id_profesor { get; set; }

    public string tipo_transaccion { get; set; }

    public decimal dias { get; set; }

    public int fines_semana { get; set; }

    public DateTime fecha { get; set; }

    public string periodo { get; set; }

    public string detalle { get; set; }

    public int? id_periodo_vacaciones { get; set; }

    public int? id_permiso { get; set; }

    public int? registrado_por_id { get; set; }

    public virtual vac_periodos_vacacionales id_periodo_vacacionesNavigation { get; set; }

    public virtual vac_permisos id_permisoNavigation { get; set; }

    public virtual profesores id_profesorNavigation { get; set; }

    public virtual usuarios registrado_por { get; set; }
}