// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vac_configuracion
{
    public int id_config { get; set; }

    public string clave { get; set; }

    public string valor { get; set; }

    public string descripcion { get; set; }

    public bool? activo { get; set; }

    public DateTime fecha_creacion { get; set; }

    public DateTime? fecha_modificacion { get; set; }
}