// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vac_tipos_permisos
{
    public int id_tipo_permiso { get; set; }

    public string nombre { get; set; }

    public string unidad { get; set; }

    public bool requiere_adjunto { get; set; }

    public bool afecta_vacaciones { get; set; }

    public decimal? max_horas_por_solicitud { get; set; }

    public int? max_permisos_mes { get; set; }

    public bool es_calamidad_domestica { get; set; }

    public int? dias_calendario_fijos { get; set; }

    public bool es_recuperable { get; set; }

    public bool? activo { get; set; }

    public virtual ICollection<vac_permisos> vac_permisos { get; set; } = new List<vac_permisos>();
}