// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vehiculos_operacion
{
    public int idVehiculo { get; set; }

    public int? id_tipo_licencia { get; set; }

    public string id_instructor_fijo { get; set; }

    public string estado_mecanico { get; set; }

    public virtual vehiculos idVehiculoNavigation { get; set; }
}