// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vinculacionproyectosperiodos
{
    public int idProyectoPeriodo { get; set; }

    public int? idProyectoVinculacion { get; set; }

    public string idPeriodo { get; set; }

    public sbyte? esPrincipal { get; set; }

    public sbyte? activo { get; set; }

    public virtual vinculacionproyectos idProyectoVinculacionNavigation { get; set; }
}