// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vinculacionproyectospresupuestos
{
    public int idProyectoPresupuesto { get; set; }

    public int? idProyectoVinculacion { get; set; }

    public string empresa { get; set; }

    public decimal? cantidad { get; set; }

    public int? orden { get; set; }

    public sbyte? activo { get; set; }

    public virtual vinculacionproyectos idProyectoVinculacionNavigation { get; set; }
}