// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vinculacionproyectospoblaciones
{
    public int idProyectosPoblaciones { get; set; }

    public int? idProyectoVinculacion { get; set; }

    public string nombre { get; set; }

    public string direccion { get; set; }

    public string telefono { get; set; }

    public string email { get; set; }

    public string contacto { get; set; }

    public DateTime? fechaRegistro { get; set; }

    public sbyte activo { get; set; }

    public virtual vinculacionproyectos idProyectoVinculacionNavigation { get; set; }
}