// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vinculacionlineasaccion
{
    public int idlineaAsccion { get; set; }

    public string linea { get; set; }

    public sbyte? activo { get; set; }

    public virtual ICollection<vinculacionproyectos> vinculacionproyectos { get; set; } = new List<vinculacionproyectos>();
}