// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vinculacionproyectoscarreras
{
    public int idProyectoCarrera { get; set; }

    public int? idProyectoVinculacion { get; set; }

    public int? idCarrera { get; set; }

    public sbyte? esPrincipal { get; set; }

    public sbyte? activo { get; set; }

    public virtual carreras idCarreraNavigation { get; set; }

    public virtual vinculacionproyectos idProyectoVinculacionNavigation { get; set; }
}