// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vinculacionpoblaciondirecta
{
    public int idPoblacionDirecta { get; set; }

    public string directa { get; set; }

    public sbyte activo { get; set; }
}