// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vinculacionestadosproyectos
{
    public int idEstadoProyecto { get; set; }

    public string estado { get; set; }

    public int? orden { get; set; }

    public sbyte? activo { get; set; }
}