// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vinculacionproyectosentidades
{
    public int idProyectoEntidad { get; set; }

    public int? idProyectoVinculacion { get; set; }

    public string entidad { get; set; }

    public string tipoEntidad { get; set; }

    public sbyte? activo { get; set; }

    public virtual vinculacionproyectos idProyectoVinculacionNavigation { get; set; }
}