// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vinculacionsubarea
{
    public int idSubArea { get; set; }

    public int? idArea { get; set; }

    public string subArea { get; set; }

    public sbyte activo { get; set; }

    public virtual vinculacionarea idAreaNavigation { get; set; }

    public virtual ICollection<vinculacionsubareaespecifica> vinculacionsubareaespecifica { get; set; } = new List<vinculacionsubareaespecifica>();
}