// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vinculacionproyectosalumnos
{
    public int idProyectoAlumno { get; set; }

    public int? idProyectoVinculacion { get; set; }

    public int? idMatricula { get; set; }

    public sbyte? activo { get; set; }

    public virtual matriculas idMatriculaNavigation { get; set; }

    public virtual vinculacionproyectos idProyectoVinculacionNavigation { get; set; }
}