// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vinculacionimpactosproyectos
{
    public int idImpactoproyecto { get; set; }

    public string impactoProyecto { get; set; }

    public sbyte? activo { get; set; }

    public virtual ICollection<vinculacionproyectosimpactos> vinculacionproyectosimpactos { get; set; } = new List<vinculacionproyectosimpactos>();
}