// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vinculacionpoblacionexterna
{
    public int idPoblacionExterna { get; set; }

    public string externa { get; set; }

    public sbyte activo { get; set; }
}