// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vinculacionproyectosresponsables
{
    public int idProyectoResponsable { get; set; }

    public int? idProyectoVinculacion { get; set; }

    public string idProfesor { get; set; }

    public sbyte? esColaborador { get; set; }

    public sbyte? activo { get; set; }

    public virtual vinculacionproyectos idProyectoVinculacionNavigation { get; set; }
}