// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vinculacionobjetivosoportunidades
{
    public int idObjetivoOportunidad { get; set; }

    public int? idCategoriaObjetivoOportunidad { get; set; }

    public string objetivoOportunidad { get; set; }

    public sbyte? activo { get; set; }

    public virtual vinculacioncategoriasobjetivosoportunidades idCategoriaObjetivoOportunidadNavigation { get; set; }

    public virtual ICollection<vinculacionproyectosobjetivosoportunidades> vinculacionproyectosobjetivosoportunidades { get; set; } = new List<vinculacionproyectosobjetivosoportunidades>();
}