// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vinculacioncategoriasobjetivosoportunidades
{
    public int idCategoriaObjetivoOportunidad { get; set; }

    public string categoriaObjetivoOportunidad { get; set; }

    public sbyte? activo { get; set; }

    public virtual ICollection<vinculacionobjetivosoportunidades> vinculacionobjetivosoportunidades { get; set; } = new List<vinculacionobjetivosoportunidades>();
}