// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vinculacionobjetivospedis
{
    public int idObjetivoPedi { get; set; }

    public string pedi { get; set; }

    public string objetivoPedi { get; set; }

    public sbyte? activo { get; set; }

    public virtual ICollection<vinculacionproyectosobjetivospedis> vinculacionproyectosobjetivospedis { get; set; } = new List<vinculacionproyectosobjetivospedis>();
}