// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vinculaciontipospoblaciones
{
    public int idTipoPoblacion { get; set; }

    public string tipoPoblacion { get; set; }

    public sbyte? activo { get; set; }

    public virtual ICollection<vinculacionproyectoscarrerasdetalle> vinculacionproyectoscarrerasdetalle { get; set; } = new List<vinculacionproyectoscarrerasdetalle>();
}