// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vinculacionprogramas
{
    public int idPrograma { get; set; }

    public string programa { get; set; }

    public string descripcion { get; set; }

    public DateOnly? fechaInicio { get; set; }

    public DateOnly? fechaFin { get; set; }

    public sbyte? activo { get; set; }
}