// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vinculacionarea
{
    public int idArea { get; set; }

    public string area { get; set; }

    public sbyte activo { get; set; }

    public virtual ICollection<vinculacionsubarea> vinculacionsubarea { get; set; } = new List<vinculacionsubarea>();
}