// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.Domain.Entities;

public partial class vinculacionhabilidadesblandas
{
    public int idHablidadBlanda { get; set; }

    public string habilidadBlanda { get; set; }

    public string descripcion { get; set; }

    public sbyte? activo { get; set; }

    public virtual ICollection<vinculacionproyectoshabilidadesblandas> vinculacionproyectoshabilidadesblandas { get; set; } = new List<vinculacionproyectoshabilidadesblandas>();
}